CREATE OR REPLACE PROCEDURE DISHA_MART_ANALYTICS.REGULATORY_MART.LOAD_BORROWER_MORTGAGE_MART_V1("START_DATE" DATE DEFAULT DATE_ADDMONTHSTODATE(-1, CURRENT_DATE()))
RETURNS VARCHAR(255)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
	PROC_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.REGULATORY_MART.LOAD_BORROWER_MORTGAGE_MART_V1'';
	TBL_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART'';
    TOTAL_ROWS_IN_PREFINAL INTEGER DEFAULT 0;
    ROWS_INSERTED INTEGER DEFAULT 0;
    ROWS_UPDATED INTEGER DEFAULT 0;
    ROWS_UNCHANGED INTEGER DEFAULT 0;
    DUPLICATE_COUNT INTEGER;
    DUPLICATE_DETAILS VARCHAR(2000);
    CURR_TIME TIMESTAMP := TO_VARCHAR(CURRENT_TIMESTAMP());
    ERROR_MESSAGE VARCHAR(1000);
    FINAL_OUTPUT VARCHAR(4000);
BEGIN

	
    -- STEP 1: Initialize date parameters for the current month
    LET MONTH_START_DATE DATE := DATE_TRUNC(''MONTH'',:START_DATE);
    LET MONTH_END_DATE DATE := LAST_DAY(:START_DATE);
    
    -- CREATE TABLE IF IT DOESN''T EXIST
    CREATE TABLE IF NOT EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART (
        DAILY_DATE DATE,
        ddate DATE,
        IBANKID INTEGER,
        sbloanno  VARCHAR(255),
        scin  VARCHAR(255),
        CollateralID  VARCHAR(255),
        sporptype  VARCHAR(10),
        spropadd  VARCHAR(2000),
        nlandarea  FLOAT,
        nbuildingarea  FLOAT,
        stownname  VARCHAR(500),
        sdistrict  VARCHAR(255),
        sstate  VARCHAR(255),
        ipin  VARCHAR(255),
        sruralurban  VARCHAR(255),
        npropvalatsanct  number(38,2),
        npresentvalue  number(38,2),
        sinsurance  VARCHAR(255)
    );
		   -- STEP 2: CLEAN EXISTING DATA FOR GIVEN MONTH
    DELETE FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART
    WHERE ddate = LAST_DAY(:START_DATE);
	
	-- STEP : CLEAN UP TEMPORARY TABLES
	DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_CURRENT_MONTH_LOAN;
	DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART_PREFINAL;
		
  
    -- STEP 3: CREATE TEMPORARY TABLE FOR ACTIVE LOANS WITH SPECIFIC CRITERIA
    CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_CURRENT_MONTH_LOAN AS
    SELECT 
        TRIM(LD.LOAN_NO) AS LOAN_ACCOUNT_NUMBER, 
        CRF.CUST_ID_FLEX AS PRIMARY_CUST_ID
    FROM 
        (SELECT 
            TRIM(LOAN_NO) AS LOAN_NO, CUST_ID_FLEX AS CUST_ID_FLEX,
            DATE(FIRST_DISBURSAL_DATE) AS FIRST_DISBURSAL_DATE, LOAN_CLOSURE_DATE
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1
        ) LD 
    LEFT JOIN 
        (SELECT CUST_ID_FLEX, TRIM(CUSTOMER_TYPE) AS CUSTOMER_TYPE
         FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_DETAILS_FLEXCUBE WHERE ACTIVATION_FLAG=1
        ) CDF
        ON LD.CUST_ID_FLEX = CDF.CUST_ID_FLEX 
    LEFT JOIN 
        (SELECT TRIM(LOAN_NO) AS LOAN_NO, TRIM(ACCT_CUST_REL) AS ACCT_CUST_REL, CUST_ID_FLEX
         FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_ROLE_FLEXCUBE WHERE ACTIVATION_FLAG=1
        ) CRF 
        ON LD.LOAN_NO = CRF.LOAN_NO
    WHERE 
        LD.FIRST_DISBURSAL_DATE >= :MONTH_START_DATE 
        AND LD.FIRST_DISBURSAL_DATE <= :MONTH_END_DATE
        AND CDF.CUSTOMER_TYPE = ''I''
        AND LD.LOAN_CLOSURE_DATE IS NULL 
        AND CRF.ACCT_CUST_REL IN (''JAF'', ''SOW'')
		
	UNION 

		(
		/*SELECT TRIM(SBLOANNO) AS NEW_SBLOANNO,CAST(TRIM(LD1.CUST_ID_FLEX) AS INT)AS SCIN FROM DISHA_L2_CURATED.HISTORICAL_LOAD.COALESCE_STG_LOAN_FIN_MAR25 A
			LEFT JOIN  (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1) LD1
			ON NEW_SBLOANNO=TRIM(LD1.LOAN_NO)
			WHERE A.SACCNTCLOSEDDURMTH=''NO'' AND A.DDATE=DATEADD(DAY,-1,:MONTH_START_DATE)
		UNION*/
		SELECT TRIM(SBLOANNO) AS SBLOANNO,CAST(TRIM(LD1.CUST_ID_FLEX) AS INT)AS SCIN FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE A 
		LEFT JOIN  (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1) LD1
		ON SBLOANNO=TRIM(LD1.LOAN_NO) WHERE A.SACCNTCLOSEDDURMTH=''NO'' AND A.DDATE=DATEADD(DAY,-1,:MONTH_START_DATE)
		)
	;

CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART_PREFINAL(
        ddate DATE,
        IBANKID INTEGER,
        sbloanno  VARCHAR(255),
        scin  VARCHAR(255),
        CollateralID  VARCHAR(255),
        sporptype  VARCHAR(10),
        spropadd  VARCHAR(2000),
        nlandarea  FLOAT,
        nbuildingarea  FLOAT,
        stownname  VARCHAR(500),
        sdistrict  VARCHAR(255),
        sstate  VARCHAR(255),
        ipin  VARCHAR(255),
        sruralurban  VARCHAR(255),
        npropvalatsanct  number(38,2),
        npresentvalue   number(38,2),
        sinsurance  VARCHAR(255)
		)
		AS 
		SELECT 
        LAST_DAY(:START_DATE) AS ddate,
        ''1'' AS IBANKID,
        TRIM(CML.LOAN_ACCOUNT_NUMBER) AS sbloanno,
        TRIM(CML.PRIMARY_CUST_ID) AS scin,
        TRIM(CDF.COLLATERAL_ID) as CollateralID,
        -- PROPERTY TYPE MAPPING
        CASE 
            WHEN (TRIM(CDF.COLLATERAL_CODE) IN (101,109,106,104)) THEN ''TOP-02''
            WHEN (TRIM(CDF.COLLATERAL_CODE) IN (107,105,108,118)) THEN ''TOP-04''
            WHEN (TRIM(CDF.COLLATERAL_CODE) IN (102,103)) THEN ''TOP-03''
        END AS sporptype,
		REGEXP_REPLACE(ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(CDF.PLOT_NUMBER,CDF.ADDRESS_LINE1,CDF.ADDRESS_LINE2,CDF.ADDRESS_LINE3,CDF.ADDRESS_LINE4,CDF.FLOOR_NO,CDF.LANDMARK,CDF.TEHSIL,CDF.DISTRICT,CDF.PROPERTY_STATE,CDF.COUNTRY,CDF.PINCODE)), '' ''),''[,''''".#$]'', '''')  AS spropadd,
        NULL AS nlandarea,
        NULL AS nbuildingarea,
        REGEXP_REPLACE(COALESCE(CDF.LANDMARK, CDF.VILLAGE, CDF.TEHSIL),''[,''''".#$]'', '''') AS stownname,
        COALESCE(
		CASE WHEN LENGTH(cast(DISCT_CODE.code as varchar(20))) < 2 THEN LPAD(cast(DISCT_CODE.code as varchar(20)), 2, ''0'')
    ELSE cast(DISCT_CODE.code as varchar(20)) END,TRIM(UPPER(CDF.DISTRICT))) as sdistrict,
        COALESCE(CASE WHEN LENGTH(cast(STATE_CODE.code as varchar(20))) < 2 THEN LPAD(cast(STATE_CODE.code as varchar(20)), 2, ''0'')
    ELSE cast(STATE_CODE.code as varchar(20)) END,TRIM(UPPER(CDF.PROPERTY_STATE))) AS sstate,
		CASE WHEN REGEXP_LIKE(TRIM(CDF.PINCODE),''^[0-9]+$'') AND LENGTH(TRIM(CDF.PINCODE))=6 THEN CDF.PINCODE ELSE NULL END AS IPIN,
        RUT.RURAL_URBAN AS sruralurban,
        Coll_Value.COLLATERAL_VALUE AS npropvalatsanct,
        NULL AS npresentvalue,
        COALESCE(ADF_IND.ASSET_INSURANCE,''NO'') as sinsurance
    FROM 
        DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_CURRENT_MONTH_LOAN CML 
    LEFT JOIN 
        (SELECT * 
         FROM REG_UAT_BACKUP.BASE_MODEL_DATA.COLLATERAL_DETAILS_FLEXCUBE
         WHERE ACTIVATION_FLAG=1 AND COLLATERAL_TYPE_CODE = 1 
         AND REC_STAUS = ''A''
         QUALIFY ROW_NUMBER() OVER (PARTITION BY LOAN_NO ORDER BY COLLATERAL_VALUE DESC) = 1
        ) CDF
        ON TRIM(CDF.LOAN_NO) = CML.LOAN_ACCOUNT_NUMBER
	LEFT JOIN
        (SELECT LOAN_NO,SUM(COLLATERAL_VALUE) AS COLLATERAL_VALUE
         FROM REG_UAT_BACKUP.BASE_MODEL_DATA.COLLATERAL_DETAILS_FLEXCUBE
         WHERE ACTIVATION_FLAG=1 AND UPPER(TRIM(COLLATERAL_SECURED_FLAG))=''P''
         GROUP BY LOAN_NO
        ) Coll_Value
        ON TRIM(Coll_Value.LOAN_NO) = CML.LOAN_ACCOUNT_NUMBER
    LEFT JOIN (
        SELECT TRIM(LOAN_NO) AS LOAN_NO, TRIM(RURAL_URBAN) AS RURAL_URBAN
        FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.REGULATORY_RURAL_URBAN_TAGGING WHERE TO_DATE(REPORT_DATE,''DD-MM-YYYY'')=LAST_DAY(:START_DATE)
    ) RUT
        ON TRIM(RUT.LOAN_NO)=TRIM(CML.LOAN_ACCOUNT_NUMBER)
    LEFT JOIN (
        SELECT TRIM(LOAN_NO) AS LOAN_NO, CASE WHEN TRY_TO_DATE(Asset_Insurance_Expiry_Date)>=:MONTH_END_DATE THEN ''YES'' ELSE ''NO'' END AS ASSET_INSURANCE
        FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.REGULATORY_INDIVIDUAL_ASSET_INSURANCE WHERE TO_DATE(REPORT_DATE,''DD-MM-YYYY'')=LAST_DAY(:START_DATE)
    ) ADF_IND
        ON TRIM(ADF_IND.LOAN_NO)=TRIM(CML.LOAN_ACCOUNT_NUMBER)
	LEFT JOIN DISHA_L2_CURATED.BASE_MODEL_DATA.DISTRICT_CODE_MAPPING DISCT_CODE
	ON TRIM(UPPER(CDF.DISTRICT))=TRIM(DISCT_CODE.DISTRICT)
	LEFT JOIN DISHA_L2_CURATED.BASE_MODEL_DATA.STATE_CODE_MAPPING STATE_CODE
	ON TRIM(UPPER(CDF.PROPERTY_STATE))=TRIM(STATE_CODE.STATE);
		
		
		
 -- Count total rows in prefinal table
    SELECT COUNT(*) INTO :TOTAL_ROWS_IN_PREFINAL
    FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART_PREFINAL;
	
----IF TOTAL ROW COUNT 0 , Return Detailed Error
	IF (TOTAL_ROWS_IN_PREFINAL = 0) THEN
		ERROR_MESSAGE := ''PREFINAL QUERY EXECUTED SUCCESSFULLY BUT RETURNED 0 RECORDS. PLEASE VERIFY SOURCE DATA AND JOIN CONDITIONS.'';
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''PREFINAL_FAILED: '' || ERROR_MESSAGE;
	END IF;


    -- Check for duplicates with details
    WITH DUPLICATE_CHECK AS (
        SELECT 
            sbloanno,CollateralID,
            COUNT(*) AS RECORD_COUNT
        FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART_PREFINAL
        GROUP BY sbloanno,CollateralID
        HAVING COUNT(*) > 1
    )
    SELECT COUNT(*) INTO :DUPLICATE_COUNT
    FROM DUPLICATE_CHECK;
	
 -- If duplicates exist, return detailed error
    IF (DUPLICATE_COUNT > 0) THEN
          SELECT CONCAT(
            ''===== DATA LOADING FAILED =====
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Duplicate Rows Found: '', :DUPLICATE_COUNT, ''
'',
            ''ERROR: Unable to load data due to duplicate entries for sbloanno,CollateralID combination.'',''
''
        ) INTO :FINAL_OUTPUT;
		
	--INSERT AUDIT INFO INTO TABLE
	--	DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		--WHERE  PROCEDURE_NAME=:PROC_NAME
		--AND	   EXECUTION_DATE=DATE(:CURR_TIME);
		
	INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
	(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
	SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;	
        
	RETURN FINAL_OUTPUT;
    
	END IF;			
        
    -- STEP 4: INSERT DATA INTO BORROWER MORTGAGE MART
    INSERT INTO DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART(
        DAILY_DATE, 
        ddate, 
        IBANKID, 
        sbloanno, 
        scin, 
        CollateralID, 
        sporptype, 
        spropadd, 
        nlandarea, 
        nbuildingarea, 
        stownname, 
        sdistrict, 
        sstate, 
        ipin, 
        sruralurban, 
        npropvalatsanct, 
        npresentvalue, 
        sinsurance
    )
    SELECT 
        CURRENT_DATE AS DAILY_DATE,
        A.ddate,
        A.IBANKID, 
        A.sbloanno, 
        A.scin, 
        A.CollateralID, 
        coalesce(B.sporptype,A.sporptype) as sporptype, 
        coalesce(CASE WHEN TRIM(B.spropadd)='''' THEN NULL ELSE B.spropadd END ,A.spropadd) as spropadd, 
        A.nlandarea, 
        A.nbuildingarea, 
        coalesce(B.stownname,A.stownname) as stownname,
        coalesce(CASE WHEN LENGTH(cast(B.sdistrict as varchar(20))) < 2 THEN LPAD(cast(B.sdistrict as varchar(20)), 2, ''0'')
    ELSE cast(B.sdistrict as varchar(20)) END,A.sdistrict) as sdistrict,
        coalesce(CASE WHEN LENGTH(cast(B.sstate as varchar(20))) < 2 THEN LPAD(cast(B.sstate as varchar(20)), 2, ''0'')
    ELSE cast(B.sstate as varchar(20)) END,A.sstate) as sstate, 
		
        coalesce(cast(B.ipin as varchar(20)),A.ipin) as ipin, 
        coalesce(B.sruralurban,A.sruralurban) as sruralurban, 
        coalesce(B.npropvalatsanct,A.npropvalatsanct) as npropvalatsanct, 
        A.npresentvalue, 
        coalesce(B.sinsurance,A.sinsurance) as sinsurance
		FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART_PREFINAL A
		LEFT JOIN DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART B
		ON TRIM(A.sbloanno)=TRIM(B.sbloanno) AND B.DDATE=DATEADD(DAY,-1,:MONTH_START_DATE)
		--LEFT JOIN (select * from DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART WHERE ddate =LAST_DAY(DATE_ADDMONTHSTODATE(-1, :START_DATE))) B
		--ON A.sbloanno=B.sbloanno
		;

		
		        -- Count rows affected
         ROWS_INSERTED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART WHERE ddate=LAST_DAY(:START_DATE));
         ROWS_UPDATED := 0;
         ROWS_UNCHANGED := :TOTAL_ROWS_IN_PREFINAL - (:ROWS_INSERTED + :ROWS_UPDATED);
		 
		 
		 	        -- Prepare detailed output
          SELECT CONCAT(
            ''===== DATA LOADING REPORT =====
'',
            ''Process Timestamp: '', :CURR_TIME, ''
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Rows Inserted: '', :ROWS_INSERTED, ''
'',
            ''Rows Updated: '', :ROWS_UPDATED, ''
'',
            ''Rows Unchanged: '', :ROWS_UNCHANGED, ''

'',
            ''

'',
            ''Status: SUCCESSFULLY LOADED DATA INTO BORROWER_MORTGAGE_MART''
        ) INTO :FINAL_OUTPUT;
		 --INSERT AUDIT INFO INTO TABLE
		--DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		--WHERE  PROCEDURE_NAME=:PROC_NAME
		--AND	   EXECUTION_DATE=LAST_DAY(:START_DATE);
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''PASS'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
	
	 RETURN FINAL_OUTPUT;
	

-- STEP : CLEAN UP TEMPORARY TABLES
DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_CURRENT_MONTH_LOAN;
DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BORROWER_MORTGAGE_MART_PREFINAL;

EXCEPTION
        WHEN OTHER THEN
            ERROR_MESSAGE := ''ERROR IN SCD TYPE2 LOAD: '' || SQLERRM || '' (ERROR CODE: '' || sqlcode || '')'';
                        
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''DATA LOADING FAILED, '' || ERROR_MESSAGE;

END';