CREATE OR REPLACE PROCEDURE DISHA_MART_ANALYTICS.REGULATORY_MART.LOAD_SANCTION_PERIOD_MART_V2("START_DATE" DATE DEFAULT DATE_ADDMONTHSTODATE(-1, CURRENT_DATE()))
RETURNS VARCHAR(2550)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
	PROC_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.REGULATORY_MART.LOAD_SANCTION_PERIOD_MART_V2'';
	TBL_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1'';
    TOTAL_ROWS_IN_PREFINAL INTEGER DEFAULT 0;
	RURAL_URBAN_CNT INTEGER DEFAULT 0;
	BOLTON_CNT INTEGER DEFAULT 0;
    ROWS_INSERTED INTEGER DEFAULT 0;
    ROWS_UPDATED INTEGER DEFAULT 0;
    ROWS_UNCHANGED INTEGER DEFAULT 0;
    DUPLICATE_COUNT INTEGER;
    DUPLICATE_DETAILS VARCHAR(2000);
    CURR_TIME TIMESTAMP := TO_VARCHAR(CURRENT_TIMESTAMP());
    ERROR_MESSAGE VARCHAR(2000);
    FINAL_OUTPUT VARCHAR(4000);

BEGIN
	
	
    -- Calculate fiscal year start date (April 1st of current or previous year)
    LET FISCAL_START_DATE DATE := CASE 
        WHEN MONTH(START_DATE) >= 4 
        THEN TO_DATE(TO_CHAR(START_DATE, ''YYYY'') || ''-04-01'')
        ELSE TO_DATE(TO_CHAR(DATEADD(YEAR, -1, START_DATE), ''YYYY'') || ''-04-01'')
    END;  
    -- Calculate end of current month
    LET MONTH_END_DATE DATE:= LAST_DAY(START_DATE);
	----Create main table 
	CREATE TABLE IF NOT EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1 CLUSTER BY (DAILY_DATE)(
	DAILY_DATE DATE,
	LOAN_NUMBER_NEW VARCHAR(255),
	LOAN_NUMBER_OLD VARCHAR(255),
	LOAN_AMOUNT FLOAT,
	PRODUCT_NHB VARCHAR(255),
	SCHEME VARCHAR(255),
	SYSTEM_PRODUCT VARCHAR(255),
	LOAN_AUTHOR_DATE DATE,
	LOAN_TERMINATION_DATE DATE,
	CUSTOMER_TYPE VARCHAR(255),
	ASSET_CLASSIFICATION_IGAAP VARCHAR(255),
	PROPERTY_STATE VARCHAR(255),
	BRANCH_STATE VARCHAR(255),
	TAGGING_OF_CANCELLED_CASES NUMBER,
	LOAN_STATUS VARCHAR(255),
	GENDER VARCHAR(255),
	LOAN_PURPOSE VARCHAR(255),
	PROPERTY_IDENTIFIER VARCHAR(255),
	TRANSACTION_STRUCTURE VARCHAR(255),
	CRE_TAGGING VARCHAR(255),
	CRE_RH_TAGGING VARCHAR(255),
	TYPE_OF_LOAN VARCHAR(255),
	END_USE_FOR_MSME VARCHAR(255),
	TRANSACTION_EXECUTION_MODE VARCHAR(255),
	CREDIT_DECISION_IDENTIFIER VARCHAR(255),
	CASTE_CATEGORY VARCHAR(255),
	HL_BIFUR_OF_SANCTION_AMT FLOAT,
	NHL_BIFUR_OF_SANCTION_AMT FLOAT,
	CHARGES_DEDUCTED_AT_DISBURSEMENT FLOAT,
	MONTHLY_INC_OF_BORROWERS_IN_LOAN FLOAT,
	RURAL_URBAN VARCHAR(255),
	END_USE_FOR_TOP_UP_LOANS VARCHAR(255) ,
	ASSET_CLASSIFICATION_IND_AS VARCHAR(255),
	CUSTOMER_ID	VARCHAR(255),
	LOAN_SANCTION_ROI FLOAT,
	CURRENT_ROI	FLOAT,
	REPORT_DATE DATE
	);
	
	
	
	--Clean existing data for given reporting year
    DELETE FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1 WHERE REPORT_DATE= LAST_DAY(:START_DATE);
	
	SELECT COUNT(*) INTO BOLTON_CNT FROM DISHA_L2_CURATED.BOLTON.BREAKUP_LOANS WHERE EFFECTIVE_DATE=LAST_DAY(:START_DATE);

	SELECT COUNT(*) INTO RURAL_URBAN_CNT FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.REGULATORY_RURAL_URBAN_TAGGING  WHERE TO_DATE(REPORT_DATE,''DD-MM-YYYY'')=LAST_DAY(:START_DATE);
	
/*	IF (RURAL_URBAN_CNT = 0) THEN
		SELECT CONCAT(''0 records in DISHA_L2_CURATED.BASE_MODEL_DATA.RURAL_URBAN_TAGGING for REPORT_DATE='',:MONTH_END_DATE) INTO :ERROR_MESSAGE;
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''PREFINAL_FAILED: '' || ERROR_MESSAGE;
	
	END IF;	
	
	IF (BOLTON_CNT = 0) THEN
		SELECT CONCAT(''0 records in DISHA_L2_CURATED.BOLTON.BREAKUP_LOANS for 
		EFFECTIVE_DATE='',:MONTH_END_DATE) INTO :ERROR_MESSAGE;
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''PREFINAL_FAILED: '' || ERROR_MESSAGE;
	
	END IF;
	*/
	
	--DELETE TEMPORARY TABLE
	DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_FISCAL_YEAR_LOAN;
	DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1_PREFINAL;
    /*----------------------------------------------------------------------------------------
    * Step 1: Create temporary table for current fiscal year loans
    * This table identifies:
    * - New loans initiated in current fiscal year
    * - Cancelled cases from previous fiscal year
    * - Special cases with payment charges
    ----------------------------------------------------------------------------------------*/
    CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_FISCAL_YEAR_LOAN AS
    -- New loans initiated in current fiscal year
    SELECT 
        LD.LOAN_NO,
        0 AS TAGGING_OF_CANCELLED_CASES
    FROM 
        (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1 ) LD
        LEFT JOIN (
            SELECT DISTINCT LOAN_NO 
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.PAYMENT_CHARGES 
                WHERE UPPER(TRIM(SOURCE_TYPE)) = ''LOAN CANCELLATION''
                AND PROCESS_DATE BETWEEN :FISCAL_START_DATE AND :MONTH_END_DATE
        ) PC_EXC ON TRIM(LD.LOAN_NO) = TRIM(PC_EXC.LOAN_NO)    
        LEFT JOIN (
            SELECT DISTINCT LOAN_NO 
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS 
                WHERE ACTIVATION_FLAG=1
				AND LOAN_CLOSURE_DATE BETWEEN :FISCAL_START_DATE AND :MONTH_END_DATE
                AND LOAN_INITIATION_DATE BETWEEN :FISCAL_START_DATE AND :MONTH_END_DATE
				AND DISB_NUMBER = 0 
				AND LOAN_STATUS = 1 
        ) LD_EXC ON TRIM(LD.LOAN_NO) = TRIM(LD_EXC.LOAN_NO)    
    WHERE 
        PC_EXC.LOAN_NO IS NULL 
        AND LD_EXC.LOAN_NO IS NULL 
        AND LD.LOAN_INITIATION_DATE BETWEEN :FISCAL_START_DATE AND :MONTH_END_DATE

    UNION

    -- Cancelled cases from previous fiscal year
    SELECT 
        DISTINCT LOAN_NO,
        1 AS TAGGING_OF_CANCELLED_CASES
    FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS  LD 
    WHERE ACTIVATION_FLAG=1
		AND LOAN_CLOSURE_DATE BETWEEN :FISCAL_START_DATE AND :MONTH_END_DATE
        AND LOAN_INITIATION_DATE < :FISCAL_START_DATE 
        AND DISB_NUMBER = 0
        AND LOAN_STATUS = 1

    UNION

    -- Special cases with payment charges
    SELECT 
        LD.LOAN_NO,
        -1 AS TAGGING_OF_CANCELLED_CASES
    FROM (
        SELECT LOAN_NO 
        FROM REG_UAT_BACKUP.BASE_MODEL_DATA.PAYMENT_CHARGES 
        WHERE UPPER(TRIM(SOURCE_TYPE)) = ''LOAN CANCELLATION''
            AND PROCESS_DATE BETWEEN :FISCAL_START_DATE AND :MONTH_END_DATE
    ) PC 
    JOIN (
        SELECT LOAN_NO 
        FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1
        AND LOAN_INITIATION_DATE < :FISCAL_START_DATE 
            AND DISB_NUMBER <> 0
    ) LD ON PC.LOAN_NO = LD.LOAN_NO;

    /*----------------------------------------------------------------------------------------
    * Step 2: Create final sanction mart table
    * Consolidates information from multiple sources including:
    * - Loan details
    * - Customer information
    * - Collateral details
    * - Transaction structures
    * - Charges and credit information
    ----------------------------------------------------------------------------------------*/
    
    CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1_PREFINAL(
	LOAN_NUMBER_NEW VARCHAR(255),
	LOAN_NUMBER_OLD VARCHAR(255),
	LOAN_AMOUNT FLOAT,
	PRODUCT_NHB VARCHAR(255),
	SCHEME VARCHAR(255),
	SYSTEM_PRODUCT VARCHAR(255),
	LOAN_AUTHOR_DATE DATE,
	LOAN_TERMINATION_DATE DATE,
	CUSTOMER_TYPE VARCHAR(255),
	ASSET_CLASSIFICATION_IGAAP VARCHAR(255),
	PROPERTY_STATE VARCHAR(255),
	BRANCH_STATE VARCHAR(255),
	TAGGING_OF_CANCELLED_CASES NUMBER,
	LOAN_STATUS VARCHAR(255),
	GENDER VARCHAR(255),
	LOAN_PURPOSE VARCHAR(255),
	PROPERTY_IDENTIFIER VARCHAR(255),
	TRANSACTION_STRUCTURE VARCHAR(255),
	CRE_TAGGING VARCHAR(255),
	CRE_RH_TAGGING VARCHAR(255),
	TYPE_OF_LOAN VARCHAR(255),
	END_USE_FOR_MSME VARCHAR(255),
	TRANSACTION_EXECUTION_MODE VARCHAR(255),
	CREDIT_DECISION_IDENTIFIER VARCHAR(255),
	CASTE_CATEGORY VARCHAR(255),
	HL_BIFUR_OF_SANCTION_AMT FLOAT,
	NHL_BIFUR_OF_SANCTION_AMT FLOAT,
	CHARGES_DEDUCTED_AT_DISBURSEMENT FLOAT,
	MONTHLY_INC_OF_BORROWERS_IN_LOAN FLOAT,
	RURAL_URBAN VARCHAR(255),
	END_USE_FOR_TOP_UP_LOANS VARCHAR(255) ,
	ASSET_CLASSIFICATION_IND_AS VARCHAR(255),
	CUSTOMER_ID	VARCHAR(255),
	LOAN_SANCTION_ROI FLOAT,
	CURRENT_ROI	FLOAT
 ) AS
    
	SELECT 
		LOAN_NUMBER_NEW, LOAN_NUMBER_OLD, LOAN_AMOUNT, PRODUCT_NHB, SCHEME, SYSTEM_PRODUCT, LOAN_AUTHOR_DATE, LOAN_TERMINATION_DATE, CUSTOMER_TYPE, ASSET_CLASSIFICATION_IGAAP, PROPERTY_STATE, BRANCH_STATE, TAGGING_OF_CANCELLED_CASES, LOAN_STATUS, GENDER, LOAN_PURPOSE, PROPERTY_IDENTIFIER, TRANSACTION_STRUCTURE, CRE_TAGGING, CRE_RH_TAGGING, TYPE_OF_LOAN, END_USE_FOR_MSME, TRANSACTION_EXECUTION_MODE, CREDIT_DECISION_IDENTIFIER, CASTE_CATEGORY,
		CASE WHEN UPPER(TRIM(PRODUCT_NHB)) = ''OTHER LOAN'' THEN 0.00 
			  WHEN UPPER(TRIM(PRODUCT_NHB)) <> ''OTHER LOAN'' THEN LOAN_AMOUNT - CHARGES_DEDUCTED_AT_DISBURSEMENT END AS HL_BIFUR_OF_SANCTION_AMT,
		CASE WHEN UPPER(TRIM(PRODUCT_NHB)) = ''OTHER LOAN'' THEN LOAN_AMOUNT
			  WHEN UPPER(TRIM(PRODUCT_NHB)) <> ''OTHER LOAN'' THEN CHARGES_DEDUCTED_AT_DISBURSEMENT END AS NHL_BIFUR_OF_SANCTION_AMT,
		CHARGES_DEDUCTED_AT_DISBURSEMENT, MONTHLY_INC_OF_BORROWERS_IN_LOAN,
		RURAL_URBAN,
		END_USE_FOR_TOP_UP_LOANS,
		ASSET_CLASSIFICATION_IND_AS,
		CUSTOMER_ID,
		LOAN_SANCTION_ROI,
		CURRENT_ROI
		FROM (
	SELECT 

        TRIM(LD_CFY.LOAN_NO) AS LOAN_NUMBER_NEW,
        TRIM(LD.OMNI_LOAN_NO) AS LOAN_NUMBER_OLD,
        LD.LOAN_SANCTION_AMOUNT AS LOAN_AMOUNT,
        --LD.DISB_AMOUNT AS DISBURSED_AMOUNT,
        -- Product categorization
        CASE 
            WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) IN (''OTHER LOANS - MSME'', ''OTHER LOANS - HOME EQUITY'') THEN ''OTHER LOAN''
            WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) IN (''PURCHASE AND CONSTRUCTION'') THEN ''CONSTRUCTION''
            ELSE TRIM(LD.LOAN_PRODUCT_NAME) 
        END AS PRODUCT_NHB,
        -- Scheme categorization
        CASE 
            WHEN UPPER(TRIM(LD.LOAN_SCHEME)) = ''G'' THEN ''GENERAL''
            WHEN UPPER(TRIM(LD.LOAN_SCHEME)) = ''EL'' THEN ''EMPLOYEE LOAN''
            WHEN UPPER(TRIM(LD.LOAN_SCHEME)) = ''S'' THEN ''STS''
            WHEN UPPER(TRIM(LD.LOAN_SCHEME)) = ''AS'' THEN ''ACE STS''
            ELSE UPPER(TRIM(LD.LOAN_SCHEME))
        END AS SCHEME,
        TRIM(LD.LOAN_PRODUCT_NAME) AS SYSTEM_PRODUCT,
        LD.LOAN_INITIATION_DATE AS LOAN_AUTHOR_DATE,
        LD.LOAN_CLOSURE_DATE AS LOAN_TERMINATION_DATE,
        -- Customer type mapping
        CASE 
            WHEN UPPER(TRIM(CDF.CUSTOMER_TYPE)) = ''I'' THEN ''INDIVIDUAL''
            WHEN UPPER(TRIM(CDF.CUSTOMER_TYPE)) = ''C'' THEN ''CORPORATE''
            ELSE NULL 
        END AS CUSTOMER_TYPE,
        TRIM(LD.ASSET_CLASS_DESC) AS ASSET_CLASSIFICATION_IGAAP,
        TRIM(COLLATERAL_DF.PROPERTY_STATE) AS PROPERTY_STATE,
		TRIM(LD.Branch_state) AS Branch_state,
        LD_CFY.TAGGING_OF_CANCELLED_CASES,
        -- Loan status mapping
        CASE 
            WHEN LD.LOAN_STATUS IN (11,1) THEN ''CLOSED''
            WHEN LD.LOAN_STATUS IN (10, 8) THEN ''ACTIVE'' 
            ELSE NULL 
        END AS LOAN_STATUS,
        -- Gender mapping
        CASE 
            WHEN UPPER(TRIM(CDF.CUST_GENDER)) = ''F'' THEN ''FEMALE''
            WHEN UPPER(TRIM(CDF.CUST_GENDER)) = ''M'' THEN ''MALE''
            ELSE NULL
        END AS GENDER,
        -- Loan purpose mapping
        UPPER(TRIM(LD.TYPE_LOAN)) AS LOAN_PURPOSE,
        -- Property identifier mapping
        UPPER(TRIM(LD.PROPERTY_IDENTIFIER)) AS PROPERTY_IDENTIFIER,
        CASE WHEN LD.CRE_TAGGING=''Y'' THEN ''CRE'' ELSE NULL END AS CRE_TAGGING,
		CASE WHEN LD.CRE_RH_TAGGING=''Y'' THEN ''CRE_RH'' ELSE NULL END AS CRE_RH_TAGGING,
        UPPER(TRIM(LD.TYPE_LOAN)) AS TYPE_OF_LOAN,
		UPPER(TRIM(LD.END_USE_FOR_MSME)) AS END_USE_FOR_MSME,
		UPPER(TRIM(LD.TRANSACTION_EXECUTION_MODE)) AS TRANSACTION_EXECUTION_MODE,
        UPPER(TRIM(LD.CREDIT_DECISION_IDENTIFIER)) AS CREDIT_DECISION_IDENTIFIER,
        TRIM(LAD.CASTE_CATEGORY) AS CASTE_CATEGORY,
        CCM.CHARGES_DEDUCTED_AT_DISBURSEMENT,
        COALESCE(MI.INCOME,0) AS MONTHLY_INC_OF_BORROWERS_IN_LOAN,
        UPPER(TRIM(LD.TRANSACTION_STRUCTURE)) AS TRANSACTION_STRUCTURE,
		TRIM(RUT.RURAL_URBAN) AS RURAL_URBAN,
		NULL AS END_USE_FOR_TOP_UP_LOANS,
		TRIM(BOLT.CLASSFICATION) AS ASSET_CLASSIFICATION_IND_AS,
		TRIM(LD.CUST_ID_FLEX) AS CUSTOMER_ID,
		LAD.LOAN_ROI AS LOAN_SANCTION_ROI, --TO BE DISCUSSED WITH Deepali.Siddahrth is taking follow up.
		LD.LOAN_CURR_RATE AS CURRENT_ROI
		
    FROM 
        (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1 ) LD 
        JOIN DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_FISCAL_YEAR_LOAN LD_CFY ON TRIM(LD.LOAN_NO)= TRIM(LD_CFY.LOAN_NO)
        LEFT JOIN (
            SELECT CUSTOMER_TYPE, CUST_ID_FLEX ,Cust_gender
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_DETAILS_FLEXCUBE WHERE ACTIVATION_FLAG=1  
        ) CDF ON TRIM(CDF.CUST_ID_FLEX )= TRIM(LD.CUST_ID_FLEX)
        LEFT JOIN (
            SELECT 
                TRIM(LOAN_NO) AS LOAN_NO,
                PROPERTY_STATE 
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.COLLATERAL_DETAILS_FLEXCUBE
                WHERE COLLATERAL_SECURED_FLAG = ''P'' AND ACTIVATION_FLAG=1
            QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(LOAN_NO) ORDER BY COLLATERAL_ID DESC) = 1
        ) COLLATERAL_DF ON TRIM(LD_CFY.LOAN_NO )= TRIM(COLLATERAL_DF.LOAN_NO)
        LEFT JOIN (
            SELECT 
                CASTE_CATEGORY,
                UNIQUE_SYS_ID,
				LOAN_ROI,
                CASE
                    WHEN LENGTH(TRIM(LOAN_APPLICATION_IDV)) = 15 
					AND SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) <> ''000000'' 
                        THEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6)
                    WHEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) = ''000000'' 
                        THEN SUBSTRING(TRIM(LMS_LOAN_NO),15,6) 
                    ELSE TRIM(LOAN_APPLICATION_IDV)
                END AS RES_LOAN_IDV
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_APPLICATION_DETAILS_TRANS WHERE ACTIVATION_FLAG=1
			
			--Qualify logic to be removed once issue resolved 
			QUALIFY ROW_NUMBER() OVER( PARTITION BY 
			(CASE
                    WHEN LENGTH(TRIM(LOAN_APPLICATION_IDV)) = 15 
					AND SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) <> ''000000'' 
                        THEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6)
                    WHEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) = ''000000'' 
                        THEN SUBSTRING(TRIM(LMS_LOAN_NO),15,6) 
                    ELSE TRIM(LOAN_APPLICATION_IDV)
                END) ORDER BY LENGTH(LOAN_APPLICATION_IDV) DESC)=1
            
        ) LAD ON TRIM(LAD.RES_LOAN_IDV) = SUBSTRING(TRIM(LD_CFY.LOAN_NO), 9, 6)
        LEFT JOIN (
            SELECT CHARGES_DEDUCTED_AT_DISBURSEMENT, LOAN_NUMBER_NEW 
            FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CHARGES_CONSOLIDATED_ORACLE 
			WHERE LOAN_NUMBER_NEW IS NOT NULL
            AND ACTIVATION_FLAG=1
        ) CCM ON TRIM(CCM.LOAN_NUMBER_NEW) = TRIM(LD_CFY.LOAN_NO)
      ----  LEFT JOIN (
		----		SELECT COALESCE(SUM(INCOME1),SUM(INCOME2)) AS MONTHLY_INCOME_ASSESSED,
		----		RES_LOAN_IDV
		----		FROM(
		----		SELECT 
      ----          INCOME1,INCOME2,
      ----          CASE
      ----              WHEN LENGTH(TRIM(LOAN_APPLICATION_IDV)) = 15 
		----			AND SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) <> ''000000'' 
      ----                  THEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6)
      ----              WHEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) = ''000000'' 
      ----                  THEN SUBSTRING(TRIM(LMS_LOAN_NO),15,6) 
      ----              ELSE TRIM(LOAN_APPLICATION_IDV)
      ----          END AS RES_LOAN_IDV
      ----      FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_APPLICATION_DETAILS_TRANS WHERE ACTIVATION_FLAG=1 AND COALESCE(INCOME1,INCOME2)  IS NOT NULL
		------Qualify logic to be removed once issue resolved 
		----	QUALIFY ROW_NUMBER() OVER( PARTITION BY 
		----	(CASE
      ----              WHEN LENGTH(TRIM(LOAN_APPLICATION_IDV)) = 15 
		----			AND SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) <> ''000000'' 
      ----                  THEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6)
      ----              WHEN SUBSTRING(TRIM(LOAN_APPLICATION_IDV),9,6) = ''000000'' 
      ----                  THEN SUBSTRING(TRIM(LMS_LOAN_NO),15,6) 
      ----              ELSE TRIM(LOAN_APPLICATION_IDV)
      ----          END) ORDER BY LENGTH(LOAN_APPLICATION_IDV) DESC)=1
		----		)A
		----		GROUP BY 
		----		RES_LOAN_IDV
		----
      ----  ) CR ON TRIM(CR.RES_LOAN_IDV) = SUBSTRING(TRIM(LD_CFY.LOAN_NO), 9, 6)
		LEFT JOIN REG_UAT_BACKUP.BASE_MODEL_DATA.CR_MONTHLY_INCOME_DETAILS AS MI ON TRIM(LD_CFY.LOAN_NO) = TRIM(MI.LAN_NEW)
		LEFT JOIN (select * FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.REGULATORY_RURAL_URBAN_TAGGING  WHERE TO_DATE(REPORT_DATE,''DD-MM-YYYY'')= LAST_DAY(:START_DATE)) RUT
			ON TRIM(LD_CFY.LOAN_NO)=TRIM(RUT.LOAN_NO)
		LEFT JOIN (SELECT * FROM DISHA_L2_CURATED.BOLTON.BREAKUP_LOANS WHERE EFFECTIVE_DATE=LAST_DAY(:START_DATE)) BOLT
			ON TRIM(LD_CFY.LOAN_NO)=TRIM(BOLT.NEW_LOAN_NO)
	)PF1;
	
 -- Count total rows in prefinal table
    SELECT COUNT(*) INTO :TOTAL_ROWS_IN_PREFINAL
    FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1_PREFINAL;
	
----IF TOTAL ROW COUNT 0 , Return Detailed Error
	IF (TOTAL_ROWS_IN_PREFINAL = 0) THEN
		ERROR_MESSAGE := ''PREFINAL QUERY EXECUTED SUCCESSFULLY BUT RETURNED 0 RECORDS. PLEASE VERIFY SOURCE DATA AND JOIN CONDITIONS.'';
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''PREFINAL_FAILED: '' || ERROR_MESSAGE;
	END IF;
	
    -- Check for duplicates with details
    WITH DUPLICATE_CHECK AS (
        SELECT 
            LOAN_NUMBER_NEW, 
            COUNT(*) AS RECORD_COUNT
        FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1_PREFINAL
        GROUP BY LOAN_NUMBER_NEW
        HAVING COUNT(*) > 1
    )
    SELECT COUNT(*) INTO :DUPLICATE_COUNT
    FROM DUPLICATE_CHECK;
	
	
	 -- If duplicates exist, return detailed error
    IF (DUPLICATE_COUNT > 0) THEN
          SELECT CONCAT(
            ''===== DATA LOADING FAILED =====
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Duplicate Rows Found: '', :DUPLICATE_COUNT, ''
'',
            ''ERROR: Unable to load data due to duplicate entries for LOAN_NUMBER_NEW.'',''
''
        ) INTO :FINAL_OUTPUT;
	--INSERT AUDIT INFO INTO TABLE
		/*DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		WHERE  PROCEDURE_NAME=:PROC_NAME
		AND	   EXECUTION_DATE=DATE(:CURR_TIME);*/
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
		
        RETURN FINAL_OUTPUT;
   END IF;
	
	
	INSERT INTO DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1 (
	LOAN_NUMBER_NEW,
	LOAN_NUMBER_OLD,
	LOAN_AMOUNT,
	PRODUCT_NHB,
	SCHEME,
	SYSTEM_PRODUCT,
	LOAN_AUTHOR_DATE,
	LOAN_TERMINATION_DATE,
	CUSTOMER_TYPE,
	ASSET_CLASSIFICATION_IGAAP,
	PROPERTY_STATE,
	BRANCH_STATE,
	TAGGING_OF_CANCELLED_CASES,
	LOAN_STATUS,
	GENDER,
	LOAN_PURPOSE,
	PROPERTY_IDENTIFIER,
	TRANSACTION_STRUCTURE,
	CRE_TAGGING,
	CRE_RH_TAGGING,
	TYPE_OF_LOAN,
	END_USE_FOR_MSME,
	TRANSACTION_EXECUTION_MODE,
	CREDIT_DECISION_IDENTIFIER,
	CASTE_CATEGORY,
	HL_BIFUR_OF_SANCTION_AMT,
	NHL_BIFUR_OF_SANCTION_AMT,
	CHARGES_DEDUCTED_AT_DISBURSEMENT,
	MONTHLY_INC_OF_BORROWERS_IN_LOAN,
	RURAL_URBAN,
	END_USE_FOR_TOP_UP_LOANS,
	ASSET_CLASSIFICATION_IND_AS,
	CUSTOMER_ID,
	LOAN_SANCTION_ROI,
	CURRENT_ROI,
	DAILY_DATE,
	REPORT_DATE
	) 
	SELECT
	S.LOAN_NUMBER_NEW,
	S.LOAN_NUMBER_OLD,
	S.LOAN_AMOUNT,
	S.PRODUCT_NHB,
	S.SCHEME,
	S.SYSTEM_PRODUCT,
	S.LOAN_AUTHOR_DATE,
	S.LOAN_TERMINATION_DATE,
	S.CUSTOMER_TYPE,
	S.ASSET_CLASSIFICATION_IGAAP,
	S.PROPERTY_STATE,
	S.BRANCH_STATE,
	S.TAGGING_OF_CANCELLED_CASES,
	S.LOAN_STATUS,
	S.GENDER,
	S.LOAN_PURPOSE,
	S.PROPERTY_IDENTIFIER,
	S.TRANSACTION_STRUCTURE,
	S.CRE_TAGGING,
	S.CRE_RH_TAGGING,
	S.TYPE_OF_LOAN,
	S.END_USE_FOR_MSME,
	S.TRANSACTION_EXECUTION_MODE,
	S.CREDIT_DECISION_IDENTIFIER,
	S.CASTE_CATEGORY,
	S.HL_BIFUR_OF_SANCTION_AMT,
	S.NHL_BIFUR_OF_SANCTION_AMT,
	S.CHARGES_DEDUCTED_AT_DISBURSEMENT,
	S.MONTHLY_INC_OF_BORROWERS_IN_LOAN,
	S.RURAL_URBAN,
	S.END_USE_FOR_TOP_UP_LOANS,
	S.ASSET_CLASSIFICATION_IND_AS,
	S.CUSTOMER_ID,
	S.LOAN_SANCTION_ROI,
	S.CURRENT_ROI,
	DATE(:CURR_TIME), 
	LAST_DAY(:START_DATE)
	FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1_PREFINAL S;
	
	
	
		        -- Count rows affected
         ROWS_INSERTED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1 WHERE REPORT_DATE=LAST_DAY(:START_DATE));
         ROWS_UPDATED := 0;
         ROWS_UNCHANGED := :TOTAL_ROWS_IN_PREFINAL - (:ROWS_INSERTED + :ROWS_UPDATED);
		 
		 
		 	        -- Prepare detailed output
          SELECT CONCAT(
            ''===== DATA LOADING REPORT =====
'',
            ''Process Timestamp: '', :CURR_TIME, ''
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Rows Inserted: '', :ROWS_INSERTED, ''
'',
            ''Rows Updated: '', :ROWS_UPDATED, ''
'',
            ''Rows Unchanged: '', :ROWS_UNCHANGED, ''

'',
            ''

'',
            ''Status: SUCCESSFULLY LOADED DATA INTO SANCTION_PERIOD_MART_V2''
        ) INTO :FINAL_OUTPUT;
		--INSERT AUDIT INFO INTO TABLE
		/*DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		WHERE  PROCEDURE_NAME=:PROC_NAME
		AND	   EXECUTION_DATE=DATE(:CURR_TIME);*/
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''PASS'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
		
	 RETURN FINAL_OUTPUT;
	
	    -- Step : Clean up temporary tables
    --DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_FISCAL_YEAR_LOAN;
    --DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1_PREFINAL;
	
	EXCEPTION
        WHEN OTHER THEN
            ERROR_MESSAGE := ''ERROR IN SCD TYPE2 LOAD: '' || SQLERRM || '' (ERROR CODE: '' || sqlcode || '')'';
                        
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''DATA LOADING FAILED, '' || ERROR_MESSAGE;

END';