CREATE OR REPLACE PROCEDURE DISHA_MART_ANALYTICS.REGULATORY_MART.LOAD_BORROWER_LOAN_DETAILS_MART_WITH_COALESCE("START_DATE" DATE DEFAULT DATE_ADDMONTHSTODATE(-1, CURRENT_DATE()))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
	PROC_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.REGULATORY_MART.LOAD_BORROWER_LOAN_DETAILS_MART_WITH_COALESCE'';
	TBL_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE'';
    TOTAL_ROWS_IN_PREFINAL INTEGER DEFAULT 0;
    ROWS_INSERTED INTEGER DEFAULT 0;
    ROWS_UPDATED INTEGER DEFAULT 0;
    ROWS_UNCHANGED INTEGER DEFAULT 0;
    DUPLICATE_COUNT INTEGER;
    DUPLICATE_DETAILS VARCHAR(2000);
    CURR_TIME TIMESTAMP := TO_VARCHAR(CURRENT_TIMESTAMP());
    ERROR_MESSAGE VARCHAR(1000);
    FINAL_OUTPUT VARCHAR(4000);
	
	BEGIN

	
    -- STEP 1: Initialize date parameters for the current month
    LET MONTH_START_DATE DATE := DATE_TRUNC(''MONTH'',:START_DATE);
    LET MONTH_END_DATE DATE := LAST_DAY(:START_DATE);
	 
    
	-- STEP : CLEAN UP TEMPORARY TABLES
	DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_MONTH_BORROWER_LOAN_DETAILS;
	DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE_PREFINAL;
	
    -- STEP 3: CREATE TEMPORARY TABLE FOR ACTIVE LOANS
    CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_MONTH_BORROWER_LOAN_DETAILS AS
    SELECT
	DISTINCT 
		TRIM(LD.LOAN_NO) AS LOAN_ACCOUNT_NUMBER,
		CAST(CRF.CUST_ID_FLEX  as INT)AS PRIMARY_CUST_ID
	FROM (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS
	WHERE LOAN_CLOSURE_DATE IS NULL AND ACTIVATION_FLAG=1) LD
		LEFT JOIN (
			SELECT CUST_ID_FLEX,CUSTOMER_TYPE 
			FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_DETAILS_FLEXCUBE WHERE ACTIVATION_FLAG=1
		) CDF 
			ON TRIM(LD.CUST_ID_FLEX) = TRIM(CDF.CUST_ID_FLEX)
		LEFT JOIN (
			SELECT LOAN_NO,ACCT_CUST_REL,CUST_ID_FLEX 
			FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_ROLE_FLEXCUBE WHERE ACTIVATION_FLAG=1
		) CRF 
			ON TRIM(LD.LOAN_NO) = TRIM(CRF.LOAN_NO)
			WHERE UPPER(TRIM(CRF.ACCT_CUST_REL)) IN (''JAF'', ''SOW'') AND UPPER(TRIM(CDF.CUSTOMER_TYPE)) = ''I'' 
			AND LD.FIRST_DISBURSAL_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE
		UNION 

		(
		/*SELECT TRIM(SBLOANNO) As NEW_SBLOANNO,CAST(TRIM(LD1.CUST_ID_FLEX) AS INT)AS SCIN FROM DISHA_L2_CURATED.HISTORICAL_LOAD.COALESCE_STG_LOAN_FIN_MAR25 A
			LEFT JOIN  (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1) LD1
			ON NEW_SBLOANNO=TRIM(LD1.LOAN_NO)
			WHERE A.SACCNTCLOSEDDURMTH=''NO'' AND A.DDATE=DATEADD(DAY,-1,:MONTH_START_DATE)
		UNION*/
		SELECT  SBLOANNO,CAST(TRIM(LD1.CUST_ID_FLEX) AS INT)AS SCIN FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE A 
		LEFT JOIN  (SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1) LD1
		ON SBLOANNO=TRIM(LD1.LOAN_NO) WHERE A.SACCNTCLOSEDDURMTH=''NO'' AND A.DDATE=LAST_DAY(DATE_ADDMONTHSTODATE(-1, :START_DATE))
		)
		
		;
		
	CREATE TABLE IF NOT EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE
	(
	DAILY_DATE date,
	ddate DATE,
	IBANKID Number(38,0),
	sbloanno VARCHAR(255),
	scin VARCHAR(255),
	sloantype VARCHAR(255),
	sloanpurpose VARCHAR(255),
	nsanctamount number(38,2),
	dsanctdate Date,
	sdwellingunit VARCHAR(255),
	imoratoriumperiod Number(38,0),
	iloantencont Number(38,0),
	iloantenresidual VARCHAR(255),
	nroi number(38,2),
	sinttype VARCHAR(255),
	nemi number(38,2),
	npreemi number(38,2),
	dfirstdisbdate Date,
	demistartdate Date,
	dpreemistartdate Date,
	nloandisbduringmonth number(38,2),
	ncummuloandisb number(38,2),
	sloanstatus VARCHAR(255),
	namtundercons number(38,2),
	spartyname VARCHAR(255),
	smortguratee number(38,2),
	namoutunderguar number(38,2),
	ntotalloanout number(38,2),
	npout number(38,2),
	niout number(38,2),
	notherdueout number(38,2),
	nloandsbp number(38,2),
	ntotalloanoverdue number(38,2),
	npoverdue number(38,2),
	nioverdue number(38,2),
	notheroverdue number(38,2),
	saccntcloseddurmth VARCHAR(255),
	sassetcat VARCHAR(255),
	secl VARCHAR(255),
	dclassdate Date,
	npd float,
	nlgd float,
	nprovamt number(38,2),
	nrw VARCHAR(255),
	sreffromnhb VARCHAR(255),
	sunderpmayclss VARCHAR(255),
	sserfaseiact float,
	namtclaimundernotice number(38,2),
	namtrecovered number(38,2),
	sstaygranted float,
	sbname VARCHAR(255),
	dbdob Date,
	sbcitizenship VARCHAR(255),
	sbpanno VARCHAR(255),
	AADHARNUMBERMASKED VARCHAR(255),
	saadhaar VARCHAR(255),
	sidtype VARCHAR(255),
	sidnumber VARCHAR(255),
	nbmonthlyincome number(38,2),
	sbreligion VARCHAR(255),
	sbcast VARCHAR(255),
	sbgender VARCHAR(255),
	sboccupation VARCHAR(255),
	nloanrepaydurmth number(38,2),
	INTEREST_ACCRUED_BUT_NOT_DUE number(38,2),
	CAR_OUTSTANDING number(38,2),
	CAR_CLASSIFICATION VARCHAR(2500)

);

	   -- STEP 2: CLEAN EXISTING DATA FOR GIVEN MONTH
    DELETE FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE
    WHERE ddate = LAST_DAY(:START_DATE);
		
	-- STEP 4: CREATE PRE-FINAL MART WITH ALL REQUIRED CALCULATIONS
	CREATE TEMPORARY TABLE DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE_PREFINAL(
	ddate DATE,
	IBANKID Number(38,0),
	sbloanno VARCHAR(255),
	scin VARCHAR(255),
	sloantype VARCHAR(255),
	sloanpurpose VARCHAR(255),
	nsanctamount number(38,2),
	dsanctdate Date,
	sdwellingunit VARCHAR(255),
	imoratoriumperiod Number(38,0),
	iloantencont Number(38,0),
	iloantenresidual VARCHAR(255),
	nroi number(38,2),
	sinttype VARCHAR(255),
	nemi number(38,2),
	npreemi number(38,2),
	dfirstdisbdate Date,
	demistartdate Date,
	dpreemistartdate Date,
	nloandisbduringmonth number(38,2),
	ncummuloandisb number(38,2),
	sloanstatus VARCHAR(255),
	namtundercons number(38,2),
	spartyname VARCHAR(255),
	smortguratee number(38,2),
	namoutunderguar number(38,2),
	npout number(38,2),
	niout number(38,2),
	notherdueout number(38,2),
	nloandsbp number(38,2),
	npoverdue number(38,2),
	nioverdue number(38,2),
	notheroverdue number(38,2),
	saccntcloseddurmth VARCHAR(255),
	sassetcat VARCHAR(255),
	secl VARCHAR(255),
	dclassdate Date,
	npd float,
	nlgd float,
	nprovamt number(38,2),
	sreffromnhb VARCHAR(255),
	sunderpmayclss VARCHAR(255),
	sserfaseiact float,
	namtclaimundernotice number(38,2),
	namtrecovered number(38,2),
	sstaygranted float,
	sbname VARCHAR(255),
	dbdob Date,
	sbcitizenship VARCHAR(255),
	sbpanno VARCHAR(255),
	AADHARNUMBERMASKED VARCHAR(255),
	saadhaar VARCHAR(255),
	sidtype VARCHAR(255),
	sidnumber VARCHAR(255),
	nbmonthlyincome number(38,2),
	sbreligion VARCHAR(255),
	sbcast VARCHAR(255),
	sbgender VARCHAR(255),
	sboccupation VARCHAR(255),
	INTEREST_ACCRUED_BUT_NOT_DUE number(38,2),
	CAR_OUTSTANDING number(38,2),
	CAR_CLASSIFICATION VARCHAR(2500),
	nrw varchar(255),
	REPAYMENT_DURING_MONTH FLOAT
	) AS
	
	SELECT
	ddate, IBANKID, sbloanno, scin, sloantype, sloanpurpose, nsanctamount, dsanctdate, sdwellingunit, imoratoriumperiod, iloantencont, iloantenresidual, nroi, sinttype, nemi, npreemi, dfirstdisbdate, demistartdate, dpreemistartdate, nloandisbduringmonth, ncummuloandisb, sloanstatus, namtundercons, spartyname, smortguratee, namoutunderguar, npout, niout, notherdueout, nloandsbp, npoverdue, nioverdue, notheroverdue, saccntcloseddurmth, sassetcat, secl, dclassdate, npd, nlgd, nprovamt, sreffromnhb, sunderpmayclss, sserfaseiact, namtclaimundernotice, namtrecovered, sstaygranted, sbname, dbdob, sbcitizenship, sbpanno, AADHARNUMBERMASKED, saadhaar, sidtype, sidnumber, nbmonthlyincome, sbreligion, sbcast, sbgender, sboccupation, INTEREST_ACCRUED_BUT_NOT_DUE,
	CAR_OUTSTANDING,CAR_CLASSIFICATION,
	nrw,
	REPAYMENT_DURING_MONTH
	FROM
	(
	
	SELECT
	ddate, IBANKID, TRIM(sbloanno) as sbloanno, TRIM(scin) as scin, sloantype, sloanpurpose, nsanctamount, dsanctdate, sdwellingunit, imoratoriumperiod, iloantencont, iloantenresidual, nroi, sinttype, nemi, npreemi, dfirstdisbdate, demistartdate, dpreemistartdate, nloandisbduringmonth, ncummuloandisb, sloanstatus, namtundercons, spartyname, smortguratee, namoutunderguar, npout, niout, notherdueout, nloandsbp, npoverdue, nioverdue, notheroverdue, saccntcloseddurmth, sassetcat, secl, dclassdate, npd, nlgd, nprovamt,nrw, sreffromnhb, sunderpmayclss, sserfaseiact, namtclaimundernotice, namtrecovered, sstaygranted, sbname, dbdob, sbcitizenship, sbpanno, AADHARNUMBERMASKED, saadhaar, sidtype, sidnumber, nbmonthlyincome, sbreligion, sbcast, sbgender, sboccupation, INTEREST_ACCRUED_BUT_NOT_DUE,
	CAR_OUTSTANDING,
	CAR_CLASSIFICATION,
	REPAYMENT_DURING_MONTH
	/*CASE
    WHEN UPPER(TRIM(LOAN_SCHEME)) = ''EL'' THEN ''STAFF LOANS''
    WHEN POOL_ID LIKE ''%PTC%'' THEN ''PTC''
    WHEN UPPER(TRIM(CRE_TAGGING)) = ''YES'' THEN ''CRE''
    WHEN UPPER(TRIM(CRE_RH_TAGGING)) = ''YES'' THEN ''CRE-RH''
    WHEN CAR_OUTSTANDING <= 3000000 AND DYNAMIC_LTV <= 80 THEN ''IND-HL-<=30L, LTV <=80%''
    WHEN CAR_OUTSTANDING <= 3000000 AND DYNAMIC_LTV > 80 AND DYNAMIC_LTV <= 90 THEN ''IND-HL-<=30L, LTV 80-90%''
    WHEN CAR_OUTSTANDING > 3000000 AND CAR_OUTSTANDING <= 7500000 AND DYNAMIC_LTV = 75 AND LOAN_AUTHOR_DATE < ''2017-08-01'' THEN ''IND-HL 30-75L LTV 75% BEFORE AUG. 17''
    WHEN CAR_OUTSTANDING > 3000000 AND CAR_OUTSTANDING <= 7500000 AND DYNAMIC_LTV > 75 AND DYNAMIC_LTV <= 80 AND LOAN_AUTHOR_DATE < ''2017-08-01'' THEN ''INDHL-30-75L, LTV 75-80%, BEFORE AUG. 17''
    WHEN CAR_OUTSTANDING > 3000000 AND CAR_OUTSTANDING <= 7500000 AND DYNAMIC_LTV <= 80 AND LOAN_AUTHOR_DATE >= ''2017-08-01'' THEN ''INDHL-30-75L, LTV <=80%, ON OR AFTER 1 AUG. 17''
    WHEN CAR_OUTSTANDING > 7500000 AND DYNAMIC_LTV <= 75 AND LOAN_AUTHOR_DATE < ''2017-08-01'' THEN ''INDHL >75L LTV <=75%, BEFORE 1 AUG. 17''
    WHEN CAR_OUTSTANDING > 7500000 AND DYNAMIC_LTV <= 75 AND LOAN_AUTHOR_DATE >= ''2017-08-01'' THEN ''INDHL >75L LTV <=75%, AFTER OR 1 AUG. 17''
    WHEN UPPER(TRIM(LOAN_PRODUCT_NAME)) IN (''Other Loans - MSME'',''Other Loans - Home Equity'') THEN ''NON HOUSING LOANS''
    WHEN UPPER(COALESCE(TRIM(LOAN_PRODUCT_NAME),''NULL'')) NOT IN (''Other Loans - MSME'',''Other Loans - Home Equity'') THEN ''OTHER HOUSING LOANS''
    END AS CAR_CLASSIFICATION,*/
	FROM
	(
	
	SELECT 
	ddate, IBANKID, sbloanno, scin, sloantype, sloanpurpose, nsanctamount, dsanctdate, sdwellingunit, imoratoriumperiod, iloantencont, iloantenresidual, nroi, sinttype, nemi, npreemi, dfirstdisbdate, demistartdate, dpreemistartdate, nloandisbduringmonth, ncummuloandisb, sloanstatus, namtundercons, spartyname, smortguratee, namoutunderguar, npout, niout, notherdueout, 
	GREATEST((npout - npoverdue),0) AS nloandsbp,
	npoverdue, nioverdue, notheroverdue, saccntcloseddurmth, sassetcat, secl, dclassdate, npd, nlgd, nprovamt,nrw, sreffromnhb, sunderpmayclss, sserfaseiact, namtclaimundernotice, namtrecovered, sstaygranted, sbname, dbdob, sbcitizenship, sbpanno, AADHARNUMBERMASKED, saadhaar, sidtype, sidnumber, nbmonthlyincome, sbreligion, sbcast, sbgender, sboccupation, INTEREST_ACCRUED_BUT_NOT_DUE,
	LOAN_SCHEME,POOL_ID,CRE_TAGGING,CRE_RH_TAGGING,LOAN_PRODUCT_NAME,DYNAMIC_LTV,LOAN_AUTHOR_DATE,REPAYMENT_DURING_MONTH,
	CAR_OUTSTANDING,CAR_CLASSIFICATION
	/*
	CASE WHEN NSANCTAMOUNT > NCUMMULOANDISB THEN npout+niout+INTEREST_ACCRUED_BUT_NOT_DUE+NSANCTAMOUNT-NCUMMULOANDISB
	ELSE npout+niout+INTEREST_ACCRUED_BUT_NOT_DUE END AS CAR_OUTSTANDING*/
	
	FROM
	(
	SELECT 
		LAST_DAY(:START_DATE) AS ddate,
		''1'' AS IBANKID,
		CML.LOAN_ACCOUNT_NUMBER AS sbloanno,
		CML.PRIMARY_CUST_ID AS scin,
		CASE 
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) IN (''OTHER LOANS - MSME'', ''OTHER LOANS - HOME EQUITY'') THEN ''TOL-02''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) IN (''CONSTRUCTION'',''RESALE PROPERTY PURCHASE'',''PURCHASE'',
													''REPAIR AND RENOVATION LOAN'',''PURCHASE AND CONSTRUCTION'') THEN ''TOL-01''
			ELSE NULL
		END AS sloantype,
		CASE 
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''CONSTRUCTION'' THEN ''POL-01''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''OTHER LOANS - HOME EQUITY'' AND COALESCE(UPPER(TRIM(TYPE_LOAN)),''NULL'') <> ''ADDITIONAL FUNDING'' THEN ''POL-11''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) IN(''OTHER LOANS - HOME EQUITY'',''OTHER LOANS - MSME'') AND UPPER(TRIM(TYPE_LOAN)) = ''ADDITIONAL FUNDING'' THEN ''POL-13''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''OTHER LOANS - MSME'' AND COALESCE(UPPER(TRIM(TYPE_LOAN)),''NULL'') <> ''ADDITIONAL FUNDING'' THEN ''POL-12''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''PURCHASE'' THEN ''POL-02''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''REPAIR AND RENOVATION LOAN'' THEN ''POL-06''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''RESALE PROPERTY PURCHASE'' THEN ''POL-03''
			WHEN UPPER(TRIM(LD.LOAN_PRODUCT_NAME)) = ''PURCHASE AND CONSTRUCTION'' THEN ''POL-05''
			ELSE '' '' 
		END AS sloanpurpose,
		LD.LOAN_SANCTION_AMOUNT AS nsanctamount,
		LD.LOAN_SANCTION_DATE AS dsanctdate,
		''DU-01'' AS sdwellingunit,
		0 AS imoratoriumperiod,
		BOOK_RT.original_loan_tenure AS iloantencont,
		BOOK_RT.remaining_tenure AS iloantenresidual,
		BOOK_RT.rate_of_interest AS nroi,
		 
		CASE WHEN TRIM(UPPER(LD.LOAN_RATE_METHOD))=''FIXED'' THEN ''TOI-01''
		WHEN TRIM(UPPER(LD.LOAN_RATE_METHOD))=''FLOATING'' THEN ''TOI-02''
		ELSE ''TOI-03'' END AS sinttype,
		NULL AS nemi,
		NULL AS npreemi,
		LD.FIRST_DISBURSAL_DATE AS dfirstdisbdate,
		NULL AS demistartdate,
		NULL AS dpreemistartdate,
		COALESCE(DISB_DTL.nloandisbduringmonth,0) as nloandisbduringmonth,
		LD.DISB_AMOUNT AS ncummuloandisb,
        CPARTY.LOAN_STATUS AS sloanstatus,
		NULL AS namtundercons,
		CPARTY.COUNTER_PARTY AS spartyname,
		NULL AS smortguratee,
		NULL AS namoutunderguar,
		CASE WHEN  LD.LOAN_CLOSURE_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE THEN 0
			 ELSE COALESCE(IND_ADF.PRINCIPAL_OUTSTANDING_ASSIGNED,DULT.Total_POS)
			 END AS npout,
		CASE WHEN LD.LOAN_CLOSURE_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE THEN 0
			 WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) IN ( ''UNI SUBSTANDARD'',''UNI DOUBTFUL1 <1YR'',''UNI DOUBTFUL 1YR TO 3 YR'',''UNDOUBTFL 3 > 3YR'',''UNI LOSS'',''SARFESI UCRR'') THEN 0
			 ELSE COALESCE(IND_ADF.INTEREST_OUTSTANDING_ASSIGNED,DULT.Overdue_Interest+DULT.pre_emi)
			 END AS niout,
		0 AS notherdueout,
		
		
		CASE WHEN  LD.LOAN_CLOSURE_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE THEN 0 
		ELSE COALESCE(IND_ADF.PRINCIPAL_OVERDUE_ASSIGNED,DULT.overdue_prin) END AS npoverdue,
		
		CASE WHEN LD.LOAN_CLOSURE_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE THEN 0
			 WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) IN ( ''UNI SUBSTANDARD'',''UNI DOUBTFUL1 <1YR'',''UNI DOUBTFUL 1YR TO 3 YR'',''UNDOUBTFL 3 > 3YR'',''UNI LOSS'',''SARFESI UCRR'') THEN 0
			 ELSE COALESCE(IND_ADF.INTEREST_OVERDUE_ASSIGNED,DULT.Overdue_Interest+DULT.pre_emi) END AS nioverdue,
		0 AS notheroverdue,
        CASE 
            WHEN LD.LOAN_CLOSURE_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE THEN ''YES''
            ELSE ''NO''

		END AS saccntcloseddurmth,
		CASE
		WHEN LD.LOAN_CLOSURE_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE THEN ''ACC-00''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI STANDARD'' THEN  ''ACC-00''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI SMA0'' THEN  ''ACC-01''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI SMA1'' THEN  ''ACC-02''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI SMA2'' THEN  ''ACC-03''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI SUBSTANDARD'' THEN  ''ACC-04''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI DOUBTFUL1 <1YR'' THEN  ''ACC-05''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI DOUBTFUL 1YR TO 3 YR'' THEN  ''ACC-06''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNDOUBTFL 3 > 3YR'' THEN  ''ACC-07''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''UNI LOSS'' THEN  ''ACC-08''
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) = ''SARFESI UCRR'' THEN ''ACC-07'' --UPPER(TRIM(LD.ASSET_CLASS_DESC))
		END AS sassetcat,
		NULL AS secl,
		CASE
		WHEN UPPER(TRIM(LD.ASSET_CLASS_DESC)) IN (''UNI SUBSTANDARD'',''UNI DOUBTFUL1 <1YR'',''UNI DOUBTFUL 1YR TO 3 YR'',
''UNDOUBTFL 3 > 3YR'',''UNI LOSS'') THEN  
			CASE WHEN LD.NPA_DATE IS NULL OR LD.NPA_DATE =''1950-01-01'' THEN  COALESCE(MANUAL_NPA.DAT_POST,LD.NPA_DATE,:MONTH_END_DATE) ELSE COALESCE(LD.NPA_DATE,:MONTH_END_DATE)
			END 
		ELSE :MONTH_END_DATE END AS dclassdate,
		NULL AS npd,
		NULL AS nlgd,
		OTSD_MART.TOTAL_FINAL_PROVISION_AS_PER_IRAC AS nprovamt,
		CASE WHEN UPPER(TRIM(LD.NHB_REFINANCE_FLG)) IN (''Y'',''YES'') THEN ''YES'' ELSE ''NO'' END AS sreffromnhb,
		CASE WHEN UPPER(TRIM(LD.CREDIT_SUBSIDY_FLG)) IN (''Y'',''YES'') THEN ''YES'' ELSE ''NO'' END AS sunderpmayclss,
		NULL AS sserfaseiact,
		NULL AS namtclaimundernotice,
		NULL AS namtrecovered,
		NULL AS sstaygranted,
		CDF.CUST_NAME_SHORT AS sbname,
		COALESCE(CDF.DATE_OF_BIRTH,CD.CUST_DOB,CD.CUST_DOB_V) AS dbdob,
		CASE 
			WHEN UPPER(TRIM(NATIONALITY))= ''IN'' THEN ''CIT-01''
			ELSE ''N/A'' 
		END AS sbcitizenship,
		CDF.PAN_NUMBER AS sbpanno,
		AADHAR_BASE.AADHR AS AADHARNUMBERMASKED,
		COALESCE(AADHAR_BASE.WHETHER_AADHAAR_OBTAINED,''NO'') as saadhaar,
		CASE 
			WHEN (COALESCE(CDF.PAN_NUMBER,'''') != '''' OR COALESCE(CDF.PAN_NUMBER,'''') = '''') AND AADHAR_BASE.WHETHER_AADHAAR_OBTAINED = ''YES'' 
				THEN ''UIDT-02''
			WHEN COALESCE(CDF.BORROWER_VOTER_ID,'''') != '''' 
				THEN ''UIDT-01''
			WHEN COALESCE(CDF.BORROWER_VOTER_ID,'''') = '''' AND (COALESCE(CDF.BORROWER_LICENSE,'''') != '''' OR COALESCE(BORROWER_PASSPORT,'''') != '''' OR COALESCE(CKYC_NUMBER,'''') != '''')
				THEN ''UIDT-02''
		END AS sidtype,
		NULL AS sidnumber,
		CR.MONTHLY_INCOME_ASSESSED AS nbmonthlyincome,
		COALESCE(FLEX_RELIGION,SFDC_RELIGION) AS sbreligion,
		COALESCE(FLEX_CASTE,SFDC_CASTE) AS sbcast,
		CASE 
			WHEN UPPER(TRIM(CDF.CUST_GENDER))=''M'' THEN ''G-01''
			WHEN UPPER(TRIM(CDF.CUST_GENDER))=''F'' THEN ''G-02''
		ELSE ''G-03'' 
		END AS sbgender,
		CASE 
			WHEN UPPER(TRIM(CDF.CUST_CONSTITUITON)) IN (
				''SELF EMPLOYED PROFESSIONAL'',
				''SELF EMPLOYED BUSINESSPERSON'',
				''LIMITED LIABILITY PARTNERSHIP''
			) THEN ''OC-02''			
			WHEN UPPER(TRIM(CDF.CUST_CONSTITUITON)) IN (
				''MULTI-NATIONAL CORPORATION'',
				''GOVERNMENT ENTITY'',
				''CASH SALARIED'',
				''PUBLIC SECTOR UNDERTAKING'',
				''BANK SALARIED - PRIVATE'',
				''BANK SALARIED - GOVERNMENT/PSU''
			) THEN ''OC-01''			
			WHEN UPPER(TRIM(CDF.CUST_CONSTITUITON)) IN (
				''SOLE PROPRIETORSHIP'',
				''PARTNERSHIP FIRM'',
				''PRIVATE''
			) THEN ''OC-03''
			WHEN UPPER(TRIM(CDF.CUST_CONSTITUITON)) IN (
				''RETIRED / PENSIONER'',
				''PUBLIC PRIVATE PARTNERSHIP'', 
				''COMPANY - PRIVATE LIMITED'',
				''COMPANY - PUBLIC LIMITED'',
				''NOT WORKING'',
				''SOCIETY/ TRUST'',
				''STUDENT'',
				''HINDU UNDIVIDED FAMILY'',
				''ASSOCIATION OF PERSONS''
			) THEN ''OC-04''
			WHEN UPPER(TRIM(CDF.CUST_CONSTITUITON)) = ''HOMEMAKER'' AND UPPER(TRIM(CDF.CUST_GENDER))=''F'' THEN ''OC-05''
			WHEN UPPER(TRIM(CDF.CUST_CONSTITUITON)) = ''HOMEMAKER'' AND UPPER(TRIM(CDF.CUST_GENDER))=''M'' THEN ''OC-02''
			ELSE NULL
		END AS sboccupation,
		OTSD_MART.RWA_CLASSIFICATION as nrw,
		OTSD_MART.INTEREST_ACCRUED_BUT_NOT_DUE,
		OTSD_MART.CAR_OUTSTANDING,
		OTSD_MART.CAR_CLASSIFICATION,
		LD.LOAN_SCHEME,
		LD.POOL_ID,
		LD.CRE_TAGGING,
		LD.CRE_RH_TAGGING,
		LD.DYNAMIC_LTV,
		LD.LOAN_PRODUCT_NAME,
		LD.LOAN_INITIATION_DATE AS LOAN_AUTHOR_DATE,
		IND_ADF.REPAYMENT_DURING_MONTH
	FROM (
		SELECT * FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG=1 
		) LD 
	RIGHT JOIN DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_MONTH_BORROWER_LOAN_DETAILS CML 
	ON TRIM(LD.LOAN_NO)=TRIM(CML.LOAN_ACCOUNT_NUMBER) 
	LEFT JOIN(
		SELECT  COD_ACCT_NO,DATE(DAT_POST) as DAT_POST FROM REG_UAT_BACKUP.FLEX_LMS.LN_X_ACCT_NPA_DTLS WHERE ACTIVATION_FLAG=1
	)MANUAL_NPA
	ON TRIM(CML.LOAN_ACCOUNT_NUMBER)=TRIM(MANUAL_NPA.COD_ACCT_NO) 
	LEFT JOIN(
		SELECT LOAN_NO,SUM(DISBURSAL_AMOUNT) AS nloandisbduringmonth
		FROM REG_UAT_BACKUP.BASE_MODEL_DATA.DISBURSEMENT_DETAILS
		WHERE ACTIVATION_FLAG=1 AND DISBURSAL_DATE BETWEEN :MONTH_START_DATE AND :MONTH_END_DATE
		GROUP BY LOAN_NO
		) DISB_DTL 
	ON TRIM(CML.LOAN_ACCOUNT_NUMBER)=TRIM(DISB_DTL.LOAN_NO) 
	LEFT JOIN(
		SELECT *,case when UPPER(TRIM(RELIGION))= ''M'' then ''RE-02''
				when UPPER(TRIM(RELIGION))= ''B'' then ''RE-06''
				when UPPER(TRIM(RELIGION))= ''C'' then ''RE-04''
				when UPPER(TRIM(RELIGION))= ''Z'' then ''RE-07''
				when UPPER(TRIM(RELIGION))= ''H'' then ''RE-01''
				when UPPER(TRIM(RELIGION))= ''J'' then ''RE-05''
				when UPPER(TRIM(RELIGION))= ''S'' then ''RE-03''
				when UPPER(TRIM(RELIGION))= ''OTHERS'' then ''RE-08''
				else NULL end As FLEX_RELIGION,
				case when UPPER(TRIM(CASTE))= ''GENERAL'' then ''CA-01''
					 when UPPER(TRIM(CASTE))= ''ST'' then ''CA-05''
					 when UPPER(TRIM(CASTE))= ''OBC'' then ''CA-03''
					 when UPPER(TRIM(CASTE))= ''EWS'' then ''CA-02''
					 when UPPER(TRIM(CASTE))= ''SC'' then ''CA-04''
					 else NULL end AS FLEX_CASTE
				FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_DETAILS_FLEXCUBE WHERE ACTIVATION_FLAG=1
		) CDF
	ON TRIM(CML.PRIMARY_CUST_ID)=TRIM(CDF.CUST_ID_FLEX) 
	LEFT JOIN 
	(
		SELECT 
			CUST_ID,
			CASE
				WHEN LENGTH(LOAN_APPLICATION_IDV) = 15 
					 AND SUBSTRING(LOAN_APPLICATION_IDV, 9, 6) != ''000000'' 
					THEN SUBSTRING(LOAN_APPLICATION_IDV, 9, 6)
				WHEN SUBSTRING(LOAN_APPLICATION_IDV, 9, 6) = ''000000'' 
					THEN SUBSTRING(TRIM(LMS_LOAN_NO), 15, 6) 
				ELSE LOAN_APPLICATION_IDV
			END AS RES_LOAN_IDV
		FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_APPLICATION_DETAILS_TRANS
		WHERE LOAN_APPLICATION_IDV IS NOT NULL 
			AND ACTIVATION_FLAG=1
		QUALIFY ROW_NUMBER() OVER (
			PARTITION BY (CASE
				WHEN LENGTH(LOAN_APPLICATION_IDV) = 15 
					 AND SUBSTRING(LOAN_APPLICATION_IDV, 9, 6) != ''000000'' 
					THEN SUBSTRING(LOAN_APPLICATION_IDV, 9, 6)
				WHEN SUBSTRING(LOAN_APPLICATION_IDV, 9, 6) = ''000000'' 
					THEN SUBSTRING(TRIM(LMS_LOAN_NO), 15, 6) 
				ELSE LOAN_APPLICATION_IDV
			END) ORDER BY CUST_ID) = 1
	)LAD1
	ON SUBSTRING(TRIM(CML.LOAN_ACCOUNT_NUMBER),9,6)=LAD1.RES_LOAN_IDV
	LEFT JOIN 
	(
	SELECT UNIQUE_SYS_ID,CUST_DOB,CUST_DOB_V,CUSTOMER_ID,
	CASE WHEN UPPER(TRIM(CUST_RELIGION))= ''HINDU'' THEN ''RE-01''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''MUSLIM'' THEN ''RE-02''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''SIKH'' THEN ''RE-03''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''CHRISTIAN'' THEN ''RE-04''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''JAIN'' THEN ''RE-05''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''BUDDHIST'' THEN ''RE-06''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''ZOROASTRIAN'' THEN ''RE-07''
		 WHEN UPPER(TRIM(CUST_RELIGION))= ''OTHERS'' THEN ''RE-08''
		 ELSE NULL
		 END AS SFDC_RELIGION,
	CASE 
		WHEN UPPER(TRIM(CUST_CASTE_CATEGORY))= ''GENERAL'' THEN ''CA-01''
		WHEN UPPER(TRIM(CUST_CASTE_CATEGORY))= ''OBC'' THEN ''CA-03''
		WHEN UPPER(TRIM(CUST_CASTE_CATEGORY))= ''SC'' THEN ''CA-04''
		WHEN UPPER(TRIM(CUST_CASTE_CATEGORY))= ''ST'' THEN ''CA-05''
		WHEN UPPER(TRIM(CUST_CASTE_CATEGORY))= ''EWS'' THEN ''CA-02''
		ELSE NULL
		END AS SFDC_CASTE
	FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_DETAILS WHERE ACTIVATION_FLAG=1
	) CD
	ON CML.PRIMARY_CUST_ID=CAST(SUBSTRING(TRIM(CD.CUSTOMER_ID),4,8) AS INT)
	LEFT JOIN(
		SELECT 
			
			CAST(SUBSTRING(CUSTOMER_ID,4,8)  AS INT) AS CUSTOMER_ID,
			CUST_AADHAR_NO AS AADHR,
			CASE
				WHEN COALESCE(CUST_AADHAR_NO,'''')<>'''' THEN ''YES''
				ELSE ''NO''
			END AS WHETHER_AADHAAR_OBTAINED,	
		FROM REG_UAT_BACKUP.BASE_MODEL_DATA.CUSTOMER_DETAILS
		WHERE ACTIVATION_FLAG=1
		QUALIFY ROW_NUMBER() OVER (
			PARTITION BY CAST(SUBSTRING(CUSTOMER_ID,4,8)  AS INT) ORDER BY CUST_AADHAR_NO DESC) = 1)AADHAR_BASE
		ON AADHAR_BASE.CUSTOMER_ID=TRIM(CML.PRIMARY_CUST_ID)
	LEFT JOIN (
			SELECT CAST(SUBSTR(SF_CUSTOMER_ID, 4, 8) AS INT) AS CUSTOMER_ID,
			COALESCE(SUM(INCOME1),SUM(INCOME2)) AS MONTHLY_INCOME_ASSESSED FROM REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_APPLICATION_DETAILS_TRANS 
			WHERE ACTIVATION_FLAG=1  AND COALESCE(INCOME1,INCOME2) IS NOT NULL 
			GROUP BY CAST(SUBSTR(SF_CUSTOMER_ID, 4, 8) AS INT)

			--SELECT CAST(SUBSTR(A.SF_CUSTOMER_ID, 4, 8) AS INT) AS CUSTOMER_ID,
			--COALESCE(SUM(INCOME1),SUM(INCOME2)) AS MONTHLY_INCOME_ASSESSED FROM 
			--REG_UAT_BACKUP.BASE_MODEL_DATA.LOAN_APPLICATION_DETAILS_TRANS 
			--WHERE ACTIVATION_FLAG=1  AND COALESCE(INCOME1,INCOME2) IS NOT NULL 
			--GROUP BY CAST(SUBSTR(A.SF_CUSTOMER_ID, 4, 8) AS INT)
            
        ) CR ON TRIM(CML.PRIMARY_CUST_ID) = TRIM(CR.CUSTOMER_ID) 
			
	LEFT JOIN (SELECT * FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART WHERE REPORT_DATE=LAST_DAY(:START_DATE)) OTSD_MART
	ON TRIM(OTSD_MART.LOAN_NUMBER_NEW)=TRIM(CML.LOAN_ACCOUNT_NUMBER)
	LEFT JOIN (SELECT * FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.REGULATORY_INDIVIDUAL_COUNTER_PARTY WHERE TO_DATE(REPORT_DATE,''DD-MM-YYYY'')=LAST_DAY(:START_DATE)) CPARTY
	ON TRIM(CPARTY.LOAN_NO)=TRIM(CML.LOAN_ACCOUNT_NUMBER)
		LEFT JOIN (SELECT * FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.REGULATORY_INDIVIDUAL_ADF WHERE TO_DATE(REPORT_DATE,''DD-MM-YYYY'')=LAST_DAY(:START_DATE) )IND_ADF
		ON TRIM(CML.LOAN_ACCOUNT_NUMBER)=TRIM(IND_ADF.LOAN_NO)
		LEFT JOIN (select * from DISHA_L2_CURATED.HISTORICAL_LOAD.BOOKING_REPORT where DATE(extracted_date)=DATEADD(DAY,1,:MONTH_END_DATE)) BOOK_RT 
		ON TRIM(BOOK_RT.NEW_LOAN_ACCOUNT_NUMBER)=TRIM(CML.LOAN_ACCOUNT_NUMBER)
		LEFT JOIN (SELECT  EXTRACTED_DATE,TOTAL_POS,OVERDUE_INTEREST,OVERDUE_PRIN,LOAN_NO,pre_emi FROM DISHA_L2_CURATED.HISTORICAL_LOAD.COLL_DUELIST
		WHERE EXTRACTED_DATE=DATEADD(DAY,1,LAST_DAY(:START_DATE)))DULT
		ON TRIM(DULT.LOAN_NO)=TRIM(CML.LOAN_ACCOUNT_NUMBER)
	)PF1)PF2)PF3
	;
	
 -- Count total rows in prefinal table
    SELECT COUNT(*) INTO :TOTAL_ROWS_IN_PREFINAL
    FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE_PREFINAL;
	
	----IF TOTAL ROW COUNT 0 , Return Detailed Error
	IF (TOTAL_ROWS_IN_PREFINAL = 0) THEN
		ERROR_MESSAGE := ''PREFINAL QUERY EXECUTED SUCCESSFULLY BUT RETURNED 0 RECORDS. PLEASE VERIFY SOURCE DATA AND JOIN CONDITIONS.'';
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''PREFINAL_FAILED: '' || ERROR_MESSAGE;
	END IF;


    -- Check for duplicates with details
    WITH DUPLICATE_CHECK AS (
        SELECT 
            sbloanno, 
            COUNT(*) AS RECORD_COUNT
        FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE_PREFINAL
        GROUP BY sbloanno
        HAVING COUNT(*) > 1
    )
    SELECT COUNT(*) INTO :DUPLICATE_COUNT
    FROM DUPLICATE_CHECK;
	
	
	   -- If duplicates exist, return detailed error
    IF (DUPLICATE_COUNT > 0) THEN
          SELECT CONCAT(
            ''===== DATA LOADING FAILED =====
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Duplicate Rows Found: '', :DUPLICATE_COUNT, ''
'',
            ''ERROR: Unable to load data due to duplicate entries for LEAD_ID.'',''
''
        ) INTO :FINAL_OUTPUT;
						--INSERT AUDIT INFO INTO TABLE
		--DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		--WHERE  PROCEDURE_NAME=:PROC_NAME
		--AND	   EXECUTION_DATE=DATE(:CURR_TIME);
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
		
        RETURN FINAL_OUTPUT;
    END IF;
	
	

	INSERT INTO DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE( 
		DAILY_DATE,
		ddate,
		IBANKID,
		sbloanno,
		scin,
		sloantype,
		sloanpurpose,
		nsanctamount,
		dsanctdate,
		sdwellingunit,
		imoratoriumperiod,
		iloantencont,
		iloantenresidual,
		nroi,
		sinttype,
		nemi,
		npreemi,
		dfirstdisbdate,
		demistartdate,
		dpreemistartdate,
		nloandisbduringmonth,
		ncummuloandisb,
		sloanstatus,
		namtundercons,
		spartyname,
		smortguratee,
		namoutunderguar,
		ntotalloanout,
		npout,
		niout,
		notherdueout,
		nloandsbp,
		ntotalloanoverdue,
		npoverdue,
		nioverdue,
		notheroverdue,
		saccntcloseddurmth,
		sassetcat,
		secl,
		dclassdate,
		npd,
		nlgd,
		nprovamt,
		nrw,
		sreffromnhb,
		sunderpmayclss,
		sserfaseiact,
		namtclaimundernotice,
		namtrecovered,
		sstaygranted,
		sbname,
		dbdob,
		sbcitizenship,
		sbpanno,
		AADHARNUMBERMASKED,
		saadhaar,
		sidtype,
		sidnumber,
		nbmonthlyincome,
		sbreligion,
		sbcast,
		sbgender,
		sboccupation,
		nloanrepaydurmth,
		INTEREST_ACCRUED_BUT_NOT_DUE,
		CAR_OUTSTANDING,
		CAR_CLASSIFICATION
	)
	SELECT
		CURRENT_DATE(),
		A.ddate,
		A.IBANKID,
		A.sbloanno,
		A.scin As scin,
		COALESCE(A.sloantype,C.sloantype) AS sloantype,
		COALESCE(A.sloanpurpose,C.sloanpurpose) AS sloanpurpose,
		A.nsanctamount,
		COALESCE(A.dsanctdate,C.dsanctdate) AS dsanctdate,
		A.sdwellingunit,
		A.imoratoriumperiod,
		COALESCE(C.iloantencont,A.iloantencont) AS iloantencont,
		A.iloantenresidual,
		A.nroi,
		A.sinttype,
		A.nemi,
		A.npreemi,
		COALESCE(A.dfirstdisbdate,C.dfirstdisbdate) AS dfirstdisbdate,
		A.demistartdate,
		A.dpreemistartdate,
		A.nloandisbduringmonth,
		A.ncummuloandisb,
		COALESCE(A.sloanstatus,C.sloanstatus,''LS-06'') as sloanstatus,
		A.namtundercons,
		COALESCE(A.spartyname,C.spartyname,''CP-06'') as spartyname,
		A.smortguratee,
		A.namoutunderguar,
		(A.npout + A.niout +A.notherdueout) AS ntotalloanout,
		A.npout,
		A.niout,
		A.notherdueout,
		A.nloandsbp,
		(A.npoverdue + A.nioverdue + A.notheroverdue) AS ntotalloanoverdue,
		A.npoverdue,
		A.nioverdue,
		A.notheroverdue,
		A.saccntcloseddurmth,
		A.sassetcat,
		A.secl,
		A.dclassdate,
		A.npd,
		A.nlgd,
		A.nprovamt,
		A.nrw,
		A.sreffromnhb,
		A.sunderpmayclss,
		A.sserfaseiact,
		A.namtclaimundernotice,
		A.namtrecovered,
		A.sstaygranted,
		COALESCE(D.sbname,A.sbname) as sbname,
		COALESCE(D.dbdob,A.dbdob) as dbdob,
		COALESCE(D.sbcitizenship,A.sbcitizenship) as sbcitizenship,
		COALESCE(D.sbpanno,A.sbpanno) as sbpanno,
		A.AADHARNUMBERMASKED,
		COALESCE(D.saadhaar, A.saadhaar) as saadhaar,
		COALESCE(D.sidtype, A.sidtype) as sidtype,
		A.sidnumber,
		COALESCE(D.nbmonthlyincome,A.nbmonthlyincome) as nbmonthlyincome,
		COALESCE(D.sbreligion,A.sbreligion) as sbreligion,
		COALESCE(D.sbcast,A.sbcast) as sbcast,
		COALESCE(D.sbgender,A.sbgender) as sbgender,
		COALESCE(D.sboccupation,A.sboccupation) as sboccupation,
		GREATEST(COALESCE(A.REPAYMENT_DURING_MONTH,(COALESCE(C.npout,0) - COALESCE(A.npout,0) + COALESCE(A.nloandisbduringmonth,0))),0) AS nloanrepaydurmth,
		A.INTEREST_ACCRUED_BUT_NOT_DUE,
		A.CAR_OUTSTANDING,
		A.CAR_CLASSIFICATION
	 
	FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE_PREFINAL A
	LEFT JOIN (SELECT * FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE WHERE DDATE=DATEADD(DAY,-1,:MONTH_START_DATE)) C
	ON TRIM(A.sbloanno)=TRIM(C.SBLOANNO)
	LEFT JOIN (SELECT scin,sbname,dbdob,sbcitizenship,sbpanno,saadhaar,sidtype,nbmonthlyincome,sbgender,sboccupation,sbreligion,sbcast FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE WHERE DDATE=DATEADD(DAY,-1,:MONTH_START_DATE) QUALIFY ROW_NUMBER() OVER(PARTITION BY SCIN ORDER BY SCIN DESC)=1) D
	ON TRIM(A.scin)=TRIM(D.scin);
	
		
		        -- Count rows affected
         ROWS_INSERTED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE WHERE ddate=LAST_DAY(:START_DATE));
         ROWS_UPDATED := 0;
         ROWS_UNCHANGED := :TOTAL_ROWS_IN_PREFINAL - (:ROWS_INSERTED + :ROWS_UPDATED);
		 
		 
		 	        -- Prepare detailed output
          SELECT CONCAT(
            ''===== DATA LOADING REPORT =====
'',
            ''Process Timestamp: '', :CURR_TIME, ''
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Rows Inserted: '', :ROWS_INSERTED, ''
'',
            ''Rows Updated: '', :ROWS_UPDATED, ''
'',
            ''Rows Unchanged: '', :ROWS_UNCHANGED, ''

'',
            ''

'',
            ''Status: SUCCESSFULLY LOADED DATA INTO BRWR_LN_DTLS_MART_WI_CLSE''
        ) INTO :FINAL_OUTPUT;
		--INSERT AUDIT INFO INTO TABLE
		/*DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		WHERE  PROCEDURE_NAME=:PROC_NAME
		AND	   EXECUTION_DATE=DATE(:CURR_TIME);*/
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''PASS'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
		
	
	 RETURN FINAL_OUTPUT;

	----For Any other exception
	EXCEPTION
        WHEN OTHER THEN
            ERROR_MESSAGE := ''ERROR IN SCD TYPE2 LOAD: '' || SQLERRM || '' (ERROR CODE: '' || sqlcode || '')'';
                        
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;	
		
		RETURN ''DATA LOADING FAILED, '' || ERROR_MESSAGE;
	

-- STEP : CLEAN UP TEMPORARY TABLES
--DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.CURRENT_MONTH_BORROWER_LOAN_DETAILS;
--DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.REGULATORY_MART.BRWR_LN_DTLS_MART_WI_CLSE_PREFINAL;
	
	
END';