CREATE OR REPLACE PROCEDURE DISHA_MART_ANALYTICS.CREDIT_RISK_MART.LOAD_RISK_LOAN_ACCOUNT_MART_DIM()
RETURNS VARCHAR(255)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE
        -- Logging Variables
    	PROC_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.CREDIT_RISK_MART.LOAD_RISK_LOAN_ACCOUNT_MART_DIM'';
    	TBL_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM'';
        TOTAL_ROWS_IN_PREFINAL INTEGER DEFAULT 0;
        ROWS_INSERTED INTEGER DEFAULT 0;
        ROWS_UPDATED INTEGER DEFAULT 0;
        ROWS_UNCHANGED INTEGER DEFAULT 0;
        DUPLICATE_COUNT INTEGER;
        DUPLICATE_DETAILS VARCHAR(2000);
        CURR_TIME TIMESTAMP := TO_VARCHAR(CURRENT_TIMESTAMP());
        ERROR_MESSAGE VARCHAR(1000);
        FINAL_OUTPUT VARCHAR(4000);
    	
    	    -- Variables for dynamic column handling
        HASH_COLUMN_LIST VARCHAR:=''S.LOAN_NO,S.CUST_ID,S.LOAN_AMOUNT,S.CURRENT_CONTRACTUAL_TENURE,S.BEHAVIOURAL_TENURE,S.LTV,S.PENDING_DISBURSAL_AMOUNT,S.DISBURSAL_STATUS,S.FIRST_DISBURSAL_DATE,S.LAST_DISBURSAL_DATE,S.CUSTOMER_CONSTITUTION,S.BRANCH_NAME,S.EMPLOYEE_CODE,S.PRODUCT,S.PRODUCT_CATEGORY,S.PROCESSING_FEES,S.HEALTH_INSURANCE_FEE,S.LIFE_INSURANCE_FEE,S.PROPERTY_INSURANCE_FEE,S.LEGAL_CHARGES,S.VALUATION_CHARGES,S.RCU_CHARGES,S.SCHEME,S.ASSET_CLASSIFICATION_DESC,S.AUM_FLAG,S.RISK_FLAG,S.PINCODE,S.BRANCH_STATE,S.TAHSIL,S.BRANCH_ID,S.DOB,S.AGE,S.SANCTION_AMOUNT_FLAG_RB,S.AFS_FLAG,S.ENCORE_FLAG,S.WRITEOFF_FLAG,S.DISBURSAL_FLAG,S.ACTIVE_LOAN_SUM,S.LOAN_STATUS,S.CLOSURE_DATE,S.CLOSURE_LOAN_COUNT_FLAG,S.ACTIVATION_FLAG'';
        INSERT_COLUMN_LIST VARCHAR;
        INSERT_VALUE_LIST VARCHAR;

        
        -- SQL statements to execute
        MERGE_STATEMENT VARCHAR(16000);
        INSERT_STATEMENT VARCHAR(16000);
    
    BEGIN
    
    	-- Step 1: Delete existing data for current date to avoid duplicates
    CREATE TABLE IF NOT EXISTS DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM (
		LOAN_NO VARCHAR(255),
		CUST_ID VARCHAR(255),
		LOAN_AMOUNT FLOAT,
		CURRENT_CONTRACTUAL_TENURE NUMBER(38,0),
		BEHAVIOURAL_TENURE NUMBER(38,0),
		LTV FLOAT,
		PENDING_DISBURSAL_AMOUNT FLOAT,
		DISBURSAL_STATUS VARCHAR(255),
		FIRST_DISBURSAL_DATE TIMESTAMP, 
		LAST_DISBURSAL_DATE TIMESTAMP,
		CUSTOMER_CONSTITUTION VARCHAR(255),
		BRANCH_NAME VARCHAR(255),
		EMPLOYEE_CODE VARCHAR(255),
		PRODUCT VARCHAR(255),
		PRODUCT_CATEGORY VARCHAR(255),
		PROCESSING_FEES FLOAT,
		HEALTH_INSURANCE_FEE FLOAT,
		LIFE_INSURANCE_FEE FLOAT,
		PROPERTY_INSURANCE_FEE FLOAT,
		LEGAL_CHARGES FLOAT,
		VALUATION_CHARGES FLOAT,
		RCU_CHARGES FLOAT,
		SCHEME VARCHAR(255),
		ASSET_CLASSIFICATION_DESC VARCHAR(255),
		AUM_FLAG VARCHAR(255),
		RISK_FLAG VARCHAR(255),
		PINCODE VARCHAR(255),
		BRANCH_STATE VARCHAR(255),
		TAHSIL VARCHAR(255),
		BRANCH_ID VARCHAR(255),
		DOB DATE,
		AGE NUMBER(38,0),
		SANCTION_AMOUNT_FLAG_RB VARCHAR(255),
		AFS_FLAG INTEGER,
    	ENCORE_FLAG INTEGER,
    	WRITEOFF_FLAG INTEGER,
		DISBURSAL_FLAG VARCHAR(255),
		ACTIVE_LOAN_SUM INTEGER,
		LOAN_STATUS VARCHAR(255),
		CLOSURE_DATE TIMESTAMP,
		CLOSURE_LOAN_COUNT_FLAG INTEGER,
		ACTIVATION_FLAG INTEGER,
		ROW_HASH VARCHAR AS SHA2(UPPER(ARRAY_TO_STRING([LOAN_NO,CUST_ID,LOAN_AMOUNT,CURRENT_CONTRACTUAL_TENURE,BEHAVIOURAL_TENURE,LTV,PENDING_DISBURSAL_AMOUNT,DISBURSAL_STATUS,FIRST_DISBURSAL_DATE,LAST_DISBURSAL_DATE,CUSTOMER_CONSTITUTION,BRANCH_NAME,EMPLOYEE_CODE,PRODUCT,PRODUCT_CATEGORY,PROCESSING_FEES,HEALTH_INSURANCE_FEE,LIFE_INSURANCE_FEE,PROPERTY_INSURANCE_FEE,LEGAL_CHARGES,VALUATION_CHARGES,RCU_CHARGES,SCHEME,ASSET_CLASSIFICATION_DESC,AUM_FLAG,RISK_FLAG,PINCODE,BRANCH_STATE,TAHSIL,BRANCH_ID,DOB,AGE,SANCTION_AMOUNT_FLAG_RB,AFS_FLAG,ENCORE_FLAG,WRITEOFF_FLAG,DISBURSAL_FLAG,ACTIVE_LOAN_SUM,LOAN_STATUS,CLOSURE_DATE,CLOSURE_LOAN_COUNT_FLAG,ACTIVATION_FLAG], ''|'')), 256),
		START_TIMESTAMP TIMESTAMP,
		END_TIMESTAMP TIMESTAMP,
		CURRENT_FLAG BOOLEAN
	);
    	
    	
		DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL;
    
    	CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL
    	(
    	LOAN_NO VARCHAR(255),
		CUST_ID VARCHAR(255),
		LOAN_AMOUNT FLOAT,
		CURRENT_CONTRACTUAL_TENURE NUMBER(38,0),
		BEHAVIOURAL_TENURE NUMBER(38,0),
		LTV FLOAT,
		PENDING_DISBURSAL_AMOUNT FLOAT,
		DISBURSAL_STATUS VARCHAR(255),
		FIRST_DISBURSAL_DATE TIMESTAMP, 
		LAST_DISBURSAL_DATE TIMESTAMP,
		CUSTOMER_CONSTITUTION VARCHAR(255),
		BRANCH_NAME VARCHAR(255),
		EMPLOYEE_CODE VARCHAR(255),
		PRODUCT VARCHAR(255),
		PRODUCT_CATEGORY VARCHAR(255),
		PROCESSING_FEES FLOAT,
		HEALTH_INSURANCE_FEE FLOAT,
		LIFE_INSURANCE_FEE FLOAT,
		PROPERTY_INSURANCE_FEE FLOAT,
		LEGAL_CHARGES FLOAT,
		VALUATION_CHARGES FLOAT,
		RCU_CHARGES FLOAT,
		SCHEME VARCHAR(255),
		ASSET_CLASSIFICATION_DESC VARCHAR(255),
		AUM_FLAG VARCHAR(255),
		RISK_FLAG VARCHAR(255),
		PINCODE VARCHAR(255),
		BRANCH_STATE VARCHAR(255),
		TAHSIL VARCHAR(255),
		BRANCH_ID VARCHAR(255),
		DOB DATE,
		AGE NUMBER(38,0),
		SANCTION_AMOUNT_FLAG_RB VARCHAR(255),
		AFS_FLAG INTEGER,
    	ENCORE_FLAG INTEGER,
    	WRITEOFF_FLAG INTEGER,
		DISBURSAL_FLAG VARCHAR(255),
		ACTIVE_LOAN_SUM INTEGER,
		LOAN_STATUS VARCHAR(255),
		CLOSURE_DATE TIMESTAMP, 
		CLOSURE_LOAN_COUNT_FLAG INTEGER,
		ACTIVATION_FLAG INTEGER
    	) AS
    	SELECT 
    	TRIM(LOAN_NO) AS LOAN_NO,
    	TRIM(CUST_ID) AS CUST_ID,
		LOAN_AMOUNT,
    	CURRENT_CONTRACTUAL_TENURE,
    	BEHAVIOURAL_TENURE,
		LTV,
		PENDING_DISBURSAL_AMOUNT,
		TRIM(CASE WHEN PENDING_DISBURSAL_AMOUNT = 0 THEN ''FULLY DISBURSED''
    		WHEN PENDING_DISBURSAL_AMOUNT > 0 AND PENDING_DISBURSAL_AMOUNT <> LOAN_AMOUNT THEN ''PARTIALLY DISBURSED''
    		WHEN PENDING_DISBURSAL_AMOUNT = LOAN_AMOUNT THEN ''NOT DISBURSED''
    		END) AS DISBURSAL_STATUS,
		FIRST_DISBURSAL_DATE,
    	LAST_DISBURSAL_DATE,
		TRIM(CUSTOMER_CONSTITUTION) AS CUSTOMER_CONSTITUTION,
    	TRIM(BRANCH_NAME) AS BRANCH_NAME,
    	TRIM(EMPLOYEE_CODE) AS EMPLOYEE_CODE,
    	TRIM(PRODUCT) AS PRODUCT,
    	TRIM(PRODUCT_CATEGORY) AS PRODUCT_CATEGORY,
		PROCESSING_FEES,
    	HEALTH_INSURANCE_FEE,
    	LIFE_INSURANCE_FEE,
    	PROPERTY_INSURANCE_FEE,
    	LEGAL_CHARGES,
    	VALUATION_CHARGES,
    	RCU_CHARGES,
		TRIM(SCHEME) AS SCHEME,
		TRIM(ASSET_CLASSIFICATION_DESC) AS ASSET_CLASSIFICATION_DESC,
    	TRIM(AUM_FLAG) AS AUM_FLAG,
		TRIM(CASE WHEN (LOAN_STATUS=''ACTIVE'' AND (CASE WHEN PENDING_DISBURSAL_AMOUNT = 0 THEN ''FULLY DISBURSED''
    		WHEN PENDING_DISBURSAL_AMOUNT > 0 AND PENDING_DISBURSAL_AMOUNT <> LOAN_AMOUNT THEN ''PARTIALLY DISBURSED''
    		WHEN PENDING_DISBURSAL_AMOUNT = LOAN_AMOUNT THEN ''NOT DISBURSED''
    		END) IS NOT NULL AND ASSET_CLASSIFICATION_DESC=''0'' AND AUM > 0) THEN 1 ELSE 0 END) AS RISK_FLAG,
		TRIM(PINCODE) AS PINCODE,
    	TRIM(BRANCH_STATE) AS BRANCH_STATE, 
    	TRIM(TAHSIL) AS TAHSIL,
    	TRIM(BRANCH_ID) AS BRANCH_ID,
		DOB,
    	AGE,
		TRIM(SANCTION_AMOUNT_FLAG_RB) AS SANCTION_AMOUNT_FLAG_RB,  
		AFS_FLAG,
    	ENCORE_FLAG,
    	WRITEOFF_FLAG,
		TRIM(DISBURSAL_FLAG) AS DISBURSAL_FLAG,
		CASE WHEN (CASE WHEN (LOAN_STATUS=''ACTIVE'' AND (CASE WHEN PENDING_DISBURSAL_AMOUNT = 0 THEN ''FULLY DISBURSED''
    		WHEN PENDING_DISBURSAL_AMOUNT > 0 AND PENDING_DISBURSAL_AMOUNT <> LOAN_AMOUNT THEN ''PARTIALLY DISBURSED''
    		WHEN PENDING_DISBURSAL_AMOUNT = LOAN_AMOUNT THEN ''NOT DISBURSED''
    		END) IS NOT NULL 
    		AND ASSET_CLASSIFICATION_DESC=''0'' AND AUM > 0) THEN 1 ELSE 0 END) = 1 THEN 1 ELSE 0 END AS ACTIVE_LOAN_SUM,
		TRIM(LOAN_STATUS) AS LOAN_STATUS,
		CLOSURE_DATE,
    	CLOSURE_LOAN_COUNT_FLAG,
    	ACTIVATION_FLAG
    	FROM
    	(
    	SELECT
			LAD.LOAN_NO,
			LAD.CUST_ID_FLEX CUST_ID,
			LAD.LOAN_SANCTION_AMOUNT AS LOAN_AMOUNT,
			LAD.LOAN_TENURE AS CURRENT_CONTRACTUAL_TENURE,
			DATEDIFF(MONTH, LAD.FIRST_DISBURSAL_DATE,LAD.LOAN_CLOSURE_DATE) AS BEHAVIOURAL_TENURE,  
			LAD.LTV_PERC LTV,
			LAD.FIRST_DISBURSAL_DATE,
			LAD.LAST_DISBURSAL_DATE,
			LAD.LOAN_SANCTION_AMOUNT - LAD.DISB_AMOUNT AS PENDING_DISBURSAL_AMOUNT,
			CDF.CUST_CONSTITUITON AS CUSTOMER_CONSTITUTION,
			LAD.BRANCH_NAME,
			LAM.EMPLOYEE_CODE AS EMPLOYEE_CODE,  
			LPM.PRODUCT_NAME AS PRODUCT,
			LAM.PRODUCT_CATEGORY,
			CC.Processing_Fees_SC_Code_1106 AS PROCESSING_FEES,
			CC.CARE_HEALTH_INSURANCE_SC_CODE_446 AS HEALTH_INSURANCE_FEE,
			(CC.Kotak_oracle+ CC.BAJAJ_ALLIANZ+ CC.INSURANCE_PREMIUM_HDFC_LIFE_SC_CODE_254+ CC.ICICI_LIFE_INSURANCE_SC_CODE_442+ CC.BHARTI_AXA_LIFE_INSURANCE_SC_CODE_443) AS LIFE_INSURANCE_FEE,
			(CC.SHRIRAM_PROPERTY_INSURANCE_SC_CODE_160+ CC.ICICI_LOMBARD_PROPERTY_INSURANCE_SC_CODE_439) AS PROPERTY_INSURANCE_FEE,
			CC.LEGAL_CHARGES_SC_CODE_1123 AS LEGAL_CHARGES,
			CC.VALUATION_CHARGES_SC_CODE_1122 AS VALUATION_CHARGES,
			CC.RCU_CHARGES_SC_CODE_1258 AS RCU_CHARGES,
			LAM.SCHEME AS SCHEME,
			CASE WHEN LAD.PRINCIPAL_OUTSTANDING IS NULL THEN ''AFS/ENCORE/WRITEOFF''  ELSE ''0'' END AS ASSET_CLASSIFICATION_DESC,
			CASE WHEN LAD.PRINCIPAL_OUTSTANDING>0 THEN ''AUM>0'' ELSE ''AUM=0'' END AS AUM_FLAG,
			CDF.CUST_PINCODE AS PINCODE,
			LAD.BRANCH_STATE,
			COLL_D_F.TEHSIL AS TAHSIL,
			LAD.LOAN_BRANCH_ID AS BRANCH_ID,
			DATE(CDF.DATE_OF_BIRTH) AS DOB,
			DATEDIFF(YEAR,CDF.DATE_OF_BIRTH,CURRENT_DATE) AS AGE,
			CASE 
				WHEN LAD.LOAN_SANCTION_AMOUNT>1000000 THEN ''B.GREATER THAN 10L'' 
				WHEN LAD.LOAN_SANCTION_AMOUNT<1000000 THEN ''A.UPTO 10L'' END AS SANCTION_AMOUNT_FLAG_RB,
			CASE WHEN AFS_OMNI.LOAN_NO IS NOT NULL THEN 1 ELSE 0 END AS AFS_FLAG,
			CASE WHEN ENCORE_OMNI.LOAN_NO IS NOT NULL THEN 1 ELSE 0 END AS ENCORE_FLAG,
			CASE WHEN TRIM(LAD.LOAN_STATUS)=''10'' THEN 1 ELSE 0 END AS WRITEOFF_FLAG,
			CASE 
				WHEN LAD.FIRST_DISBURSAL_DATE BETWEEN ''2021-04-01'' AND ''2023-03-31'' THEN ''DISBURSED BETWEEN APR_21 AND MAR_31''
				WHEN LAD.FIRST_DISBURSAL_DATE >=''2023-04-01'' THEN ''DISBURSED AFTER APR_23''
    		END AS DISBURSAL_FLAG,
			CASE 
				WHEN TRIM(LAD.LOAN_STATUS) IN(''11'',''1'',''5'') THEN ''CLOSED'' 
				WHEN TRIM(LAD.LOAN_STATUS) IN(''10'',''8'',''6'') THEN ''ACTIVE'' 
				ELSE TRIM(LAD.LOAN_STATUS) END AS LOAN_STATUS,
			LAD.LOAN_CLOSURE_DATE AS CLOSURE_DATE, 
			CASE WHEN LAD.LOAN_CLOSURE_DATE IS NOT NULL THEN 1 ELSE 0 END AS CLOSURE_LOAN_COUNT_FLAG, 
			LAD.PRINCIPAL_OUTSTANDING AS AUM,
			LAD.ACTIVATION_FLAG
    	--SELECT DISTINCT LOAN_DPD
    	FROM 
        (SELECT * FROM DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS WHERE ACTIVATION_FLAG IN (1,9)) LAD
		LEFT JOIN (SELECT TRIM(LOAN_NO) AS LOAN_NO ,UPPER(TRIM(TEHSIL)) AS TEHSIL FROM DISHA_L2_CURATED.BASE_MODEL_DATA.COLLATERAL_DETAILS_FLEXCUBE where ACTIVATION_FLAG=1 QUALIFY ROW_NUMBER() OVER(PARTITION BY LOAN_NO ORDER BY SURROGATE_ID DESC)=1)COLL_D_F
		ON TRIM(LAD.LOAN_NO)=COLL_D_F.LOAN_NO
    	LEFT JOIN (select distinct loan_no from DISHA_L2_CURATED.HISTORICAL_LOAD.AFS_SINCE_APR16) AFS_OMNI
    	ON UPPER(TRIM(LAD.OMNI_LOAN_NO))=AFS_OMNI.LOAN_NO
    	LEFT JOIN (select distinct loan_no from DISHA_L2_CURATED.HISTORICAL_LOAD.ENCORE_DATA) ENCORE_OMNI
    	ON UPPER(TRIM(LAD.OMNI_LOAN_NO))=ENCORE_OMNI.LOAN_NO
    	LEFT JOIN (SELECT * FROM DISHA_L2_CURATED.BASE_MODEL_DATA.CUSTOMER_DETAILS_FLEXCUBE WHERE  ACTIVATION_FLAG=1) CDF
    	ON TRIM(LAD.CUST_ID_FLEX)=TRIM(CDF.CUST_ID_FLEX )
    	LEFT JOIN (SELECT * FROM DISHA_L2_CURATED.BASE_MODEL_DATA.CHARGES_CONSOLIDATED_ORACLE WHERE ACTIVATION_FLAG=1) CC 
    	ON TRIM(LAD.LOAN_NO)=TRIM(CC.LOAN_NUMBER_NEW)
    	LEFT JOIN (SELECT * FROM DISHA_L2_CURATED.BASE_MODEL_DATA.PRODUCT_MASTER_FLEXCUBE WHERE ACTIVATION_FLAG=1) LPM 
    	ON TRIM(LAD.PRODUCT_ID)=TRIM(LPM.PRODUCT_ID) 
    	LEFT JOIN (SELECT * FROM DISHA_MART_ANALYTICS.SALES_CREDIT_MART.LOAN_ACCOUNT_MART WHERE ACTIVATION_FLAG=1) LAM
    	ON TRIM(LAD.LOAN_NO)=TRIM(LAM.LOAN_ACCOUNT_NUMBER)
	);
      
      -- Count total rows in prefinal table
        SELECT COUNT(*) INTO :TOTAL_ROWS_IN_PREFINAL
        FROM DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL WHERE ACTIVATION_FLAG=1;
		
     ----IF TOTAL ROW COUNT 0 , Return Detailed Error
                IF (TOTAL_ROWS_IN_PREFINAL = 0) THEN
                                ERROR_MESSAGE := ''PREFINAL QUERY EXECUTED SUCCESSFULLY BUT RETURNED 0 RECORDS. PLEASE VERIFY SOURCE DATA AND JOIN CONDITIONS.'';
                                
                                INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
                                (PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
                                SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;                
                                
                                RETURN ''PREFINAL_FAILED: '' || ERROR_MESSAGE;
                END IF;
				
        -- Check for duplicates with details
        WITH DUPLICATE_CHECK AS (
            SELECT 
                LOAN_NO, 
                COUNT(*) AS RECORD_COUNT
            FROM DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL
            GROUP BY LOAN_NO
            HAVING COUNT(*) > 1
        )
        SELECT COUNT(*) INTO :DUPLICATE_COUNT
        FROM DUPLICATE_CHECK;
        
        -- Insert column list (all columns including metadata columns)
        SELECT LISTAGG(COLUMN_NAME, '','')  WITHIN GROUP (ORDER BY ORDINAL_POSITION)|| '',START_TIMESTAMP,END_TIMESTAMP,CURRENT_FLAG''
        INTO :INSERT_COLUMN_LIST
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = ''CREDIT_RISK_MART''
        AND TABLE_NAME = ''RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL''
        AND TABLE_CATALOG = ''DISHA_MART_ANALYTICS'';
        
        -- Insert value list (dynamically mapping source columns)
        SELECT LISTAGG(''S.'' || COLUMN_NAME, '','')  WITHIN GROUP (ORDER BY ORDINAL_POSITION)
        INTO :INSERT_VALUE_LIST
        FROM DISHA_MART_ANALYTICS.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = ''CREDIT_RISK_MART''
        AND TABLE_NAME = ''RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL''
        AND TABLE_CATALOG = ''DISHA_MART_ANALYTICS'';    
      
    	
     -- If duplicates exist, return detailed error
        IF (DUPLICATE_COUNT > 0) THEN
              SELECT CONCAT(
                ''===== DATA LOADING FAILED =====
    '',
                ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
    '',
                ''Duplicate Rows Found: '', :DUPLICATE_COUNT, ''
    '',
                ''ERROR: Unable to load data due to duplicate entries for LOAN_NO.'',''
    ''
            ) INTO :FINAL_OUTPUT;
			
			--INSERT AUDIT INFO INTO TABLE
		--DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		--WHERE  PROCEDURE_NAME=:PROC_NAME
		--AND	   EXECUTION_DATE=DATE(:CURR_TIME);
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
			
            RETURN FINAL_OUTPUT;
       END IF;
    	
    	
    
           -- Perform MERGE operation with tracking
      MERGE_STATEMENT :=  	CONCAT(
        ''MERGE INTO DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM T
        USING DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL S
        ON T.LOAN_NO = S.LOAN_NO
            AND T.CURRENT_FLAG = TRUE
        WHEN MATCHED 
        AND SHA2(UPPER(ARRAY_TO_STRING(['', 
        HASH_COLUMN_LIST, 
        ''], ''''|'''')), 256) <> T.ROW_HASH
        THEN UPDATE SET 
            CURRENT_FLAG = FALSE,
            END_TIMESTAMP ='''''',CURR_TIME,'''''',
    		T.ACTIVATION_FLAG=(CASE WHEN S.ACTIVATION_FLAG=1 THEN 0 ELSE S.ACTIVATION_FLAG END)
        WHEN NOT MATCHED 
    	 AND S.ACTIVATION_FLAG=1 THEN 
        INSERT ('', 
        INSERT_COLUMN_LIST, 
        '')
        VALUES('', 
        INSERT_VALUE_LIST,'','''''',CURR_TIME,'''''',NULL,TRUE);'');
    		
    	EXECUTE IMMEDIATE :MERGE_STATEMENT;
    	
    	        -- Count rows affected
             ROWS_INSERTED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM WHERE CURRENT_FLAG=1 and START_TIMESTAMP=:CURR_TIME);
             ROWS_UPDATED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM WHERE ACTIVATION_FLAG=0 and END_TIMESTAMP=:CURR_TIME);
             ROWS_UNCHANGED := :TOTAL_ROWS_IN_PREFINAL - (:ROWS_INSERTED + :ROWS_UPDATED);
    	
    INSERT_STATEMENT:= 
    	CONCAT(''INSERT INTO DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM('',
    			INSERT_COLUMN_LIST,'')
    			SELECT '',
    			INSERT_VALUE_LIST,'','''''',CURR_TIME,'''''',NULL,TRUE 
    			FROM DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM_PREFINAL S
    			JOIN DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM T
    				ON T.LOAN_NO = S.LOAN_NO
    				AND T.CURRENT_FLAG = FALSE
    				AND S.ACTIVATION_FLAG = 1
    				AND T.END_TIMESTAMP ='''''',CURR_TIME,'''''';'');
    				
    	EXECUTE IMMEDIATE :INSERT_STATEMENT;	
    	        -- Prepare detailed output
              SELECT CONCAT(
                ''===== DATA LOADING REPORT =====
    '',
                ''Process Timestamp: '', :CURR_TIME, ''
    '',
                ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
    '',
                ''Rows Inserted: '', :ROWS_INSERTED, ''
    '',
                ''Rows Updated: '', :ROWS_UPDATED, ''
    '',
                ''Rows Unchanged: '', :ROWS_UNCHANGED, ''
    
    '',
                ''
    
    '',
                ''Status: DATA LOADED SUCCESSFULY''
            ) INTO :FINAL_OUTPUT;
    		
    		--INSERT AUDIT INFO INTO TABLE
		--DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		--WHERE  PROCEDURE_NAME=:PROC_NAME
		--AND	   EXECUTION_DATE=DATE(:CURR_TIME);
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''PASS'',:CURR_TIME,CURRENT_TIMESTAMP,:FINAL_OUTPUT;
    
            RETURN FINAL_OUTPUT;
         ----For Any other exception
                EXCEPTION
        WHEN OTHER THEN
            ERROR_MESSAGE := ''ERROR IN SCD TYPE2 LOAD: '' || SQLERRM || '' (ERROR CODE: '' || sqlcode || '')'';
                        
                                INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
                                (PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME,REMARKS)
                                SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP,:ERROR_MESSAGE;                
                                
                                RETURN ''DATA LOADING FAILED, '' || ERROR_MESSAGE;

    --EXCEPTION
    --    WHEN OTHER THEN
    --        -- Capture any unexpected errors
    --         ERROR_MESSAGE := SQLERRM;
    --        
    --        -- Prepare error output
    --          SELECT CONCAT(
    --            ''===== DATA LOADING FAILED =====
    --'',
    --            ''Error Timestamp: '', :CURR_TIME, ''
    --'',
    --            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
    --'',
    --            ''ERROR MESSAGE: '', :ERROR_MESSAGE, ''
    --'',
    --            ''Status: UNEXPECTED ERROR DURING LOADING''
    --        ) INTO :FINAL_OUTPUT;
    
    --        RETURN FINAL_OUTPUT;
    END';